// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eventManage.proto

package eventManage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetEventListReq struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	ManageId             int64    `protobuf:"varint,3,opt,name=manageId,proto3" json:"manageId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventListReq) Reset()         { *m = GetEventListReq{} }
func (m *GetEventListReq) String() string { return proto.CompactTextString(m) }
func (*GetEventListReq) ProtoMessage()    {}
func (*GetEventListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4314db4f6a3e016f, []int{0}
}

func (m *GetEventListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventListReq.Unmarshal(m, b)
}
func (m *GetEventListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventListReq.Marshal(b, m, deterministic)
}
func (m *GetEventListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventListReq.Merge(m, src)
}
func (m *GetEventListReq) XXX_Size() int {
	return xxx_messageInfo_GetEventListReq.Size(m)
}
func (m *GetEventListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventListReq proto.InternalMessageInfo

func (m *GetEventListReq) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetEventListReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetEventListReq) GetManageId() int64 {
	if m != nil {
		return m.ManageId
	}
	return 0
}

type EventMesssage struct {
	EventId              int64    `protobuf:"varint,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	EventTitle           string   `protobuf:"bytes,2,opt,name=eventTitle,proto3" json:"eventTitle,omitempty"`
	EventDescription     string   `protobuf:"bytes,3,opt,name=eventDescription,proto3" json:"eventDescription,omitempty"`
	EventType            string   `protobuf:"bytes,4,opt,name=eventType,proto3" json:"eventType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventMesssage) Reset()         { *m = EventMesssage{} }
func (m *EventMesssage) String() string { return proto.CompactTextString(m) }
func (*EventMesssage) ProtoMessage()    {}
func (*EventMesssage) Descriptor() ([]byte, []int) {
	return fileDescriptor_4314db4f6a3e016f, []int{1}
}

func (m *EventMesssage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventMesssage.Unmarshal(m, b)
}
func (m *EventMesssage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventMesssage.Marshal(b, m, deterministic)
}
func (m *EventMesssage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMesssage.Merge(m, src)
}
func (m *EventMesssage) XXX_Size() int {
	return xxx_messageInfo_EventMesssage.Size(m)
}
func (m *EventMesssage) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMesssage.DiscardUnknown(m)
}

var xxx_messageInfo_EventMesssage proto.InternalMessageInfo

func (m *EventMesssage) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *EventMesssage) GetEventTitle() string {
	if m != nil {
		return m.EventTitle
	}
	return ""
}

func (m *EventMesssage) GetEventDescription() string {
	if m != nil {
		return m.EventDescription
	}
	return ""
}

func (m *EventMesssage) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

type EventListRsp struct {
	EventList            []*EventMesssage `protobuf:"bytes,1,rep,name=eventList,proto3" json:"eventList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EventListRsp) Reset()         { *m = EventListRsp{} }
func (m *EventListRsp) String() string { return proto.CompactTextString(m) }
func (*EventListRsp) ProtoMessage()    {}
func (*EventListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4314db4f6a3e016f, []int{2}
}

func (m *EventListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventListRsp.Unmarshal(m, b)
}
func (m *EventListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventListRsp.Marshal(b, m, deterministic)
}
func (m *EventListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventListRsp.Merge(m, src)
}
func (m *EventListRsp) XXX_Size() int {
	return xxx_messageInfo_EventListRsp.Size(m)
}
func (m *EventListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_EventListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_EventListRsp proto.InternalMessageInfo

func (m *EventListRsp) GetEventList() []*EventMesssage {
	if m != nil {
		return m.EventList
	}
	return nil
}

type AddEventReq struct {
	ManageId             int64    `protobuf:"varint,1,opt,name=manageId,proto3" json:"manageId,omitempty"`
	EventTitle           string   `protobuf:"bytes,2,opt,name=eventTitle,proto3" json:"eventTitle,omitempty"`
	EventDescription     string   `protobuf:"bytes,3,opt,name=eventDescription,proto3" json:"eventDescription,omitempty"`
	EventTime            string   `protobuf:"bytes,4,opt,name=eventTime,proto3" json:"eventTime,omitempty"`
	EventNum             string   `protobuf:"bytes,5,opt,name=eventNum,proto3" json:"eventNum,omitempty"`
	EventType            string   `protobuf:"bytes,6,opt,name=eventType,proto3" json:"eventType,omitempty"`
	ProblemRandom        bool     `protobuf:"varint,7,opt,name=problemRandom,proto3" json:"problemRandom,omitempty"`
	OptionRandom         bool     `protobuf:"varint,8,opt,name=optionRandom,proto3" json:"optionRandom,omitempty"`
	AnswerTime           string   `protobuf:"bytes,9,opt,name=answerTime,proto3" json:"answerTime,omitempty"`
	CreditRule           string   `protobuf:"bytes,10,opt,name=creditRule,proto3" json:"creditRule,omitempty"`
	ParticipantNum       int32    `protobuf:"varint,11,opt,name=participantNum,proto3" json:"participantNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEventReq) Reset()         { *m = AddEventReq{} }
func (m *AddEventReq) String() string { return proto.CompactTextString(m) }
func (*AddEventReq) ProtoMessage()    {}
func (*AddEventReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4314db4f6a3e016f, []int{3}
}

func (m *AddEventReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEventReq.Unmarshal(m, b)
}
func (m *AddEventReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEventReq.Marshal(b, m, deterministic)
}
func (m *AddEventReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEventReq.Merge(m, src)
}
func (m *AddEventReq) XXX_Size() int {
	return xxx_messageInfo_AddEventReq.Size(m)
}
func (m *AddEventReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEventReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddEventReq proto.InternalMessageInfo

func (m *AddEventReq) GetManageId() int64 {
	if m != nil {
		return m.ManageId
	}
	return 0
}

func (m *AddEventReq) GetEventTitle() string {
	if m != nil {
		return m.EventTitle
	}
	return ""
}

func (m *AddEventReq) GetEventDescription() string {
	if m != nil {
		return m.EventDescription
	}
	return ""
}

func (m *AddEventReq) GetEventTime() string {
	if m != nil {
		return m.EventTime
	}
	return ""
}

func (m *AddEventReq) GetEventNum() string {
	if m != nil {
		return m.EventNum
	}
	return ""
}

func (m *AddEventReq) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *AddEventReq) GetProblemRandom() bool {
	if m != nil {
		return m.ProblemRandom
	}
	return false
}

func (m *AddEventReq) GetOptionRandom() bool {
	if m != nil {
		return m.OptionRandom
	}
	return false
}

func (m *AddEventReq) GetAnswerTime() string {
	if m != nil {
		return m.AnswerTime
	}
	return ""
}

func (m *AddEventReq) GetCreditRule() string {
	if m != nil {
		return m.CreditRule
	}
	return ""
}

func (m *AddEventReq) GetParticipantNum() int32 {
	if m != nil {
		return m.ParticipantNum
	}
	return 0
}

type AddEventRsp struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	EventId              int64    `protobuf:"varint,2,opt,name=eventId,proto3" json:"eventId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEventRsp) Reset()         { *m = AddEventRsp{} }
func (m *AddEventRsp) String() string { return proto.CompactTextString(m) }
func (*AddEventRsp) ProtoMessage()    {}
func (*AddEventRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4314db4f6a3e016f, []int{4}
}

func (m *AddEventRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEventRsp.Unmarshal(m, b)
}
func (m *AddEventRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEventRsp.Marshal(b, m, deterministic)
}
func (m *AddEventRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEventRsp.Merge(m, src)
}
func (m *AddEventRsp) XXX_Size() int {
	return xxx_messageInfo_AddEventRsp.Size(m)
}
func (m *AddEventRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEventRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AddEventRsp proto.InternalMessageInfo

func (m *AddEventRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AddEventRsp) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func init() {
	proto.RegisterType((*GetEventListReq)(nil), "GetEventListReq")
	proto.RegisterType((*EventMesssage)(nil), "EventMesssage")
	proto.RegisterType((*EventListRsp)(nil), "EventListRsp")
	proto.RegisterType((*AddEventReq)(nil), "AddEventReq")
	proto.RegisterType((*AddEventRsp)(nil), "AddEventRsp")
}

func init() { proto.RegisterFile("eventManage.proto", fileDescriptor_4314db4f6a3e016f) }

var fileDescriptor_4314db4f6a3e016f = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0x25, 0xbb, 0xec, 0x76, 0x33, 0xd9, 0x2d, 0xc5, 0x42, 0xc8, 0x5a, 0xa1, 0x2a, 0x8a, 0x10,
	0x8a, 0x00, 0xe5, 0x50, 0xae, 0x5c, 0x16, 0xa8, 0x50, 0x25, 0xb6, 0x48, 0x16, 0x37, 0x4e, 0xe9,
	0x66, 0x52, 0x59, 0x8a, 0x13, 0x13, 0xbb, 0x54, 0x3d, 0xf1, 0x11, 0x7c, 0x30, 0xc8, 0x93, 0xb4,
	0x71, 0xc2, 0x99, 0x5b, 0xde, 0x9b, 0x89, 0xfd, 0xde, 0xf8, 0x0d, 0x3c, 0xc5, 0x9f, 0x58, 0xdb,
	0x7d, 0x5e, 0xe7, 0xd7, 0x98, 0xe9, 0xb6, 0xb1, 0x4d, 0xf2, 0x1d, 0x9e, 0x7c, 0x46, 0x7b, 0xee,
	0xf8, 0x2f, 0xd2, 0x58, 0x81, 0x3f, 0xd8, 0x73, 0x58, 0x36, 0x65, 0x69, 0xd0, 0xf2, 0x20, 0x0e,
	0xd2, 0x85, 0xe8, 0x11, 0x7b, 0x06, 0x8b, 0x4a, 0x2a, 0x69, 0xf9, 0x8c, 0xe8, 0x0e, 0xb0, 0x2d,
	0xac, 0x14, 0x1d, 0x78, 0x51, 0xf0, 0x79, 0x1c, 0xa4, 0x73, 0xf1, 0x80, 0x93, 0xdf, 0x01, 0x6c,
	0xe8, 0xe8, 0x3d, 0x1a, 0x63, 0xf2, 0x6b, 0x64, 0x1c, 0x8e, 0x48, 0xc3, 0x45, 0x41, 0x87, 0xcf,
	0xc5, 0x3d, 0x64, 0xa7, 0x00, 0xf4, 0xf9, 0x4d, 0xda, 0x0a, 0xe9, 0x8a, 0x50, 0x78, 0x0c, 0x7b,
	0x0d, 0x27, 0x84, 0x3e, 0xa1, 0x39, 0xb4, 0x52, 0x5b, 0xd9, 0xd4, 0x74, 0x5f, 0x28, 0xfe, 0xe1,
	0xd9, 0x0b, 0x08, 0xbb, 0x3f, 0xef, 0x34, 0xf2, 0xc7, 0xd4, 0x34, 0x10, 0xc9, 0x7b, 0x58, 0x0f,
	0x7e, 0x8d, 0x66, 0x6f, 0xfb, 0x6e, 0x87, 0x79, 0x10, 0xcf, 0xd3, 0xe8, 0xec, 0x38, 0x1b, 0xc9,
	0x16, 0x43, 0x43, 0xf2, 0x67, 0x06, 0xd1, 0xae, 0x28, 0xa8, 0xee, 0xa6, 0xe5, 0xfb, 0x0f, 0xc6,
	0xfe, 0xff, 0x8f, 0x27, 0xa9, 0x26, 0x9e, 0xa4, 0x42, 0xa7, 0x82, 0xc0, 0xe5, 0x8d, 0xe2, 0x0b,
	0x2a, 0x3e, 0xe0, 0xf1, 0x34, 0x96, 0x93, 0x69, 0xb0, 0x97, 0xb0, 0xd1, 0x6d, 0x73, 0x55, 0xa1,
	0x12, 0x79, 0x5d, 0x34, 0x8a, 0x1f, 0xc5, 0x41, 0xba, 0x12, 0x63, 0x92, 0x25, 0xb0, 0x6e, 0x48,
	0x47, 0xdf, 0xb4, 0xa2, 0xa6, 0x11, 0xe7, 0xdc, 0xe6, 0xb5, 0xb9, 0xc5, 0x96, 0x24, 0x86, 0x9d,
	0xdb, 0x81, 0x71, 0xf5, 0x43, 0x8b, 0x85, 0xb4, 0xe2, 0xa6, 0x42, 0x0e, 0x5d, 0x7d, 0x60, 0xd8,
	0x2b, 0x38, 0xd6, 0x79, 0x6b, 0xe5, 0x41, 0xea, 0xbc, 0x73, 0x12, 0x51, 0xd0, 0x26, 0x6c, 0xb2,
	0xf3, 0x1e, 0xc0, 0x68, 0x17, 0x29, 0x85, 0xf4, 0x4c, 0x34, 0xff, 0x50, 0xdc, 0x43, 0x3f, 0x6c,
	0xb3, 0x51, 0xd8, 0xce, 0x7e, 0x41, 0x74, 0x3e, 0xac, 0x02, 0xfb, 0x08, 0xa7, 0xfe, 0x12, 0x7c,
	0xb8, 0xdb, 0xf7, 0x2f, 0xb8, 0xab, 0x8b, 0xaf, 0x65, 0x69, 0x2c, 0x3b, 0xc9, 0x26, 0x5b, 0xb2,
	0xdd, 0x64, 0x7e, 0x88, 0x92, 0x47, 0xec, 0x0d, 0xc9, 0xba, 0xc4, 0x5b, 0xe2, 0xd9, 0x3a, 0xf3,
	0x52, 0xb2, 0xf5, 0x90, 0x6b, 0xbe, 0x5a, 0xd2, 0xf6, 0xbd, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff,
	0xb2, 0x7d, 0x99, 0x2e, 0x92, 0x03, 0x00, 0x00,
}
