// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eventManage.proto

package eventManage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventIdReq struct {
	EventId              int64    `protobuf:"varint,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventIdReq) Reset()         { *m = EventIdReq{} }
func (m *EventIdReq) String() string { return proto.CompactTextString(m) }
func (*EventIdReq) ProtoMessage()    {}
func (*EventIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4314db4f6a3e016f, []int{0}
}

func (m *EventIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventIdReq.Unmarshal(m, b)
}
func (m *EventIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventIdReq.Marshal(b, m, deterministic)
}
func (m *EventIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventIdReq.Merge(m, src)
}
func (m *EventIdReq) XXX_Size() int {
	return xxx_messageInfo_EventIdReq.Size(m)
}
func (m *EventIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EventIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_EventIdReq proto.InternalMessageInfo

func (m *EventIdReq) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

type EventDetailMesssage struct {
	EventId              int64    `protobuf:"varint,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	EventTitle           string   `protobuf:"bytes,2,opt,name=eventTitle,proto3" json:"eventTitle,omitempty"`
	EventType            string   `protobuf:"bytes,3,opt,name=eventType,proto3" json:"eventType,omitempty"`
	EventDescription     string   `protobuf:"bytes,4,opt,name=eventDescription,proto3" json:"eventDescription,omitempty"`
	ParticipantNum       int32    `protobuf:"varint,5,opt,name=participantNum,proto3" json:"participantNum,omitempty"`
	StartTime            string   `protobuf:"bytes,6,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              string   `protobuf:"bytes,7,opt,name=endTime,proto3" json:"endTime,omitempty"`
	AnswerDay            string   `protobuf:"bytes,8,opt,name=answerDay,proto3" json:"answerDay,omitempty"`
	SingleScore          float64  `protobuf:"fixed64,9,opt,name=singleScore,proto3" json:"singleScore,omitempty"`
	FillScore            float64  `protobuf:"fixed64,10,opt,name=fillScore,proto3" json:"fillScore,omitempty"`
	JudgeScore           float64  `protobuf:"fixed64,11,opt,name=judgeScore,proto3" json:"judgeScore,omitempty"`
	MultipleScore        float64  `protobuf:"fixed64,12,opt,name=multipleScore,proto3" json:"multipleScore,omitempty"`
	TeamScore            float64  `protobuf:"fixed64,13,opt,name=teamScore,proto3" json:"teamScore,omitempty"`
	TeamScoreUp          float64  `protobuf:"fixed64,14,opt,name=teamScoreUp,proto3" json:"teamScoreUp,omitempty"`
	PersonScore          float64  `protobuf:"fixed64,15,opt,name=personScore,proto3" json:"personScore,omitempty"`
	PersonScoreUp        float64  `protobuf:"fixed64,16,opt,name=personScoreUp,proto3" json:"personScoreUp,omitempty"`
	Single               string   `protobuf:"bytes,17,opt,name=single,proto3" json:"single,omitempty"`
	Fill                 string   `protobuf:"bytes,18,opt,name=fill,proto3" json:"fill,omitempty"`
	Judge                string   `protobuf:"bytes,19,opt,name=judge,proto3" json:"judge,omitempty"`
	Multiple             string   `protobuf:"bytes,20,opt,name=multiple,proto3" json:"multiple,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventDetailMesssage) Reset()         { *m = EventDetailMesssage{} }
func (m *EventDetailMesssage) String() string { return proto.CompactTextString(m) }
func (*EventDetailMesssage) ProtoMessage()    {}
func (*EventDetailMesssage) Descriptor() ([]byte, []int) {
	return fileDescriptor_4314db4f6a3e016f, []int{1}
}

func (m *EventDetailMesssage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventDetailMesssage.Unmarshal(m, b)
}
func (m *EventDetailMesssage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventDetailMesssage.Marshal(b, m, deterministic)
}
func (m *EventDetailMesssage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDetailMesssage.Merge(m, src)
}
func (m *EventDetailMesssage) XXX_Size() int {
	return xxx_messageInfo_EventDetailMesssage.Size(m)
}
func (m *EventDetailMesssage) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDetailMesssage.DiscardUnknown(m)
}

var xxx_messageInfo_EventDetailMesssage proto.InternalMessageInfo

func (m *EventDetailMesssage) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *EventDetailMesssage) GetEventTitle() string {
	if m != nil {
		return m.EventTitle
	}
	return ""
}

func (m *EventDetailMesssage) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *EventDetailMesssage) GetEventDescription() string {
	if m != nil {
		return m.EventDescription
	}
	return ""
}

func (m *EventDetailMesssage) GetParticipantNum() int32 {
	if m != nil {
		return m.ParticipantNum
	}
	return 0
}

func (m *EventDetailMesssage) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *EventDetailMesssage) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *EventDetailMesssage) GetAnswerDay() string {
	if m != nil {
		return m.AnswerDay
	}
	return ""
}

func (m *EventDetailMesssage) GetSingleScore() float64 {
	if m != nil {
		return m.SingleScore
	}
	return 0
}

func (m *EventDetailMesssage) GetFillScore() float64 {
	if m != nil {
		return m.FillScore
	}
	return 0
}

func (m *EventDetailMesssage) GetJudgeScore() float64 {
	if m != nil {
		return m.JudgeScore
	}
	return 0
}

func (m *EventDetailMesssage) GetMultipleScore() float64 {
	if m != nil {
		return m.MultipleScore
	}
	return 0
}

func (m *EventDetailMesssage) GetTeamScore() float64 {
	if m != nil {
		return m.TeamScore
	}
	return 0
}

func (m *EventDetailMesssage) GetTeamScoreUp() float64 {
	if m != nil {
		return m.TeamScoreUp
	}
	return 0
}

func (m *EventDetailMesssage) GetPersonScore() float64 {
	if m != nil {
		return m.PersonScore
	}
	return 0
}

func (m *EventDetailMesssage) GetPersonScoreUp() float64 {
	if m != nil {
		return m.PersonScoreUp
	}
	return 0
}

func (m *EventDetailMesssage) GetSingle() string {
	if m != nil {
		return m.Single
	}
	return ""
}

func (m *EventDetailMesssage) GetFill() string {
	if m != nil {
		return m.Fill
	}
	return ""
}

func (m *EventDetailMesssage) GetJudge() string {
	if m != nil {
		return m.Judge
	}
	return ""
}

func (m *EventDetailMesssage) GetMultiple() string {
	if m != nil {
		return m.Multiple
	}
	return ""
}

type EventShowMesssage struct {
	EventId              int64    `protobuf:"varint,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	EventTitle           string   `protobuf:"bytes,2,opt,name=eventTitle,proto3" json:"eventTitle,omitempty"`
	EventDescription     string   `protobuf:"bytes,3,opt,name=eventDescription,proto3" json:"eventDescription,omitempty"`
	ParticipantNum       int32    `protobuf:"varint,4,opt,name=participantNum,proto3" json:"participantNum,omitempty"`
	StartTime            string   `protobuf:"bytes,5,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              string   `protobuf:"bytes,6,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Single               string   `protobuf:"bytes,7,opt,name=single,proto3" json:"single,omitempty"`
	Fill                 string   `protobuf:"bytes,8,opt,name=fill,proto3" json:"fill,omitempty"`
	Judge                string   `protobuf:"bytes,9,opt,name=judge,proto3" json:"judge,omitempty"`
	Multiple             string   `protobuf:"bytes,10,opt,name=multiple,proto3" json:"multiple,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventShowMesssage) Reset()         { *m = EventShowMesssage{} }
func (m *EventShowMesssage) String() string { return proto.CompactTextString(m) }
func (*EventShowMesssage) ProtoMessage()    {}
func (*EventShowMesssage) Descriptor() ([]byte, []int) {
	return fileDescriptor_4314db4f6a3e016f, []int{2}
}

func (m *EventShowMesssage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventShowMesssage.Unmarshal(m, b)
}
func (m *EventShowMesssage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventShowMesssage.Marshal(b, m, deterministic)
}
func (m *EventShowMesssage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventShowMesssage.Merge(m, src)
}
func (m *EventShowMesssage) XXX_Size() int {
	return xxx_messageInfo_EventShowMesssage.Size(m)
}
func (m *EventShowMesssage) XXX_DiscardUnknown() {
	xxx_messageInfo_EventShowMesssage.DiscardUnknown(m)
}

var xxx_messageInfo_EventShowMesssage proto.InternalMessageInfo

func (m *EventShowMesssage) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *EventShowMesssage) GetEventTitle() string {
	if m != nil {
		return m.EventTitle
	}
	return ""
}

func (m *EventShowMesssage) GetEventDescription() string {
	if m != nil {
		return m.EventDescription
	}
	return ""
}

func (m *EventShowMesssage) GetParticipantNum() int32 {
	if m != nil {
		return m.ParticipantNum
	}
	return 0
}

func (m *EventShowMesssage) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *EventShowMesssage) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *EventShowMesssage) GetSingle() string {
	if m != nil {
		return m.Single
	}
	return ""
}

func (m *EventShowMesssage) GetFill() string {
	if m != nil {
		return m.Fill
	}
	return ""
}

func (m *EventShowMesssage) GetJudge() string {
	if m != nil {
		return m.Judge
	}
	return ""
}

func (m *EventShowMesssage) GetMultiple() string {
	if m != nil {
		return m.Multiple
	}
	return ""
}

type GetEventListReq struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	ManageId             int64    `protobuf:"varint,3,opt,name=manageId,proto3" json:"manageId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventListReq) Reset()         { *m = GetEventListReq{} }
func (m *GetEventListReq) String() string { return proto.CompactTextString(m) }
func (*GetEventListReq) ProtoMessage()    {}
func (*GetEventListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4314db4f6a3e016f, []int{3}
}

func (m *GetEventListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventListReq.Unmarshal(m, b)
}
func (m *GetEventListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventListReq.Marshal(b, m, deterministic)
}
func (m *GetEventListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventListReq.Merge(m, src)
}
func (m *GetEventListReq) XXX_Size() int {
	return xxx_messageInfo_GetEventListReq.Size(m)
}
func (m *GetEventListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventListReq proto.InternalMessageInfo

func (m *GetEventListReq) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetEventListReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetEventListReq) GetManageId() int64 {
	if m != nil {
		return m.ManageId
	}
	return 0
}

type EventMesssage struct {
	EventId              int64    `protobuf:"varint,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	EventTitle           string   `protobuf:"bytes,2,opt,name=eventTitle,proto3" json:"eventTitle,omitempty"`
	EventDescription     string   `protobuf:"bytes,3,opt,name=eventDescription,proto3" json:"eventDescription,omitempty"`
	EventType            string   `protobuf:"bytes,4,opt,name=eventType,proto3" json:"eventType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventMesssage) Reset()         { *m = EventMesssage{} }
func (m *EventMesssage) String() string { return proto.CompactTextString(m) }
func (*EventMesssage) ProtoMessage()    {}
func (*EventMesssage) Descriptor() ([]byte, []int) {
	return fileDescriptor_4314db4f6a3e016f, []int{4}
}

func (m *EventMesssage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventMesssage.Unmarshal(m, b)
}
func (m *EventMesssage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventMesssage.Marshal(b, m, deterministic)
}
func (m *EventMesssage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMesssage.Merge(m, src)
}
func (m *EventMesssage) XXX_Size() int {
	return xxx_messageInfo_EventMesssage.Size(m)
}
func (m *EventMesssage) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMesssage.DiscardUnknown(m)
}

var xxx_messageInfo_EventMesssage proto.InternalMessageInfo

func (m *EventMesssage) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *EventMesssage) GetEventTitle() string {
	if m != nil {
		return m.EventTitle
	}
	return ""
}

func (m *EventMesssage) GetEventDescription() string {
	if m != nil {
		return m.EventDescription
	}
	return ""
}

func (m *EventMesssage) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

type EventListRsp struct {
	EventList            []*EventMesssage `protobuf:"bytes,1,rep,name=eventList,proto3" json:"eventList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EventListRsp) Reset()         { *m = EventListRsp{} }
func (m *EventListRsp) String() string { return proto.CompactTextString(m) }
func (*EventListRsp) ProtoMessage()    {}
func (*EventListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4314db4f6a3e016f, []int{5}
}

func (m *EventListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventListRsp.Unmarshal(m, b)
}
func (m *EventListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventListRsp.Marshal(b, m, deterministic)
}
func (m *EventListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventListRsp.Merge(m, src)
}
func (m *EventListRsp) XXX_Size() int {
	return xxx_messageInfo_EventListRsp.Size(m)
}
func (m *EventListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_EventListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_EventListRsp proto.InternalMessageInfo

func (m *EventListRsp) GetEventList() []*EventMesssage {
	if m != nil {
		return m.EventList
	}
	return nil
}

type AddEventReq struct {
	ManageId             int64    `protobuf:"varint,1,opt,name=manageId,proto3" json:"manageId,omitempty"`
	EventTitle           string   `protobuf:"bytes,2,opt,name=eventTitle,proto3" json:"eventTitle,omitempty"`
	EventDescription     string   `protobuf:"bytes,3,opt,name=eventDescription,proto3" json:"eventDescription,omitempty"`
	EventTime            string   `protobuf:"bytes,4,opt,name=eventTime,proto3" json:"eventTime,omitempty"`
	EventNum             string   `protobuf:"bytes,5,opt,name=eventNum,proto3" json:"eventNum,omitempty"`
	EventType            string   `protobuf:"bytes,6,opt,name=eventType,proto3" json:"eventType,omitempty"`
	ProblemRandom        bool     `protobuf:"varint,7,opt,name=problemRandom,proto3" json:"problemRandom,omitempty"`
	OptionRandom         bool     `protobuf:"varint,8,opt,name=optionRandom,proto3" json:"optionRandom,omitempty"`
	AnswerTime           string   `protobuf:"bytes,9,opt,name=answerTime,proto3" json:"answerTime,omitempty"`
	CreditRule           string   `protobuf:"bytes,10,opt,name=creditRule,proto3" json:"creditRule,omitempty"`
	ParticipantNum       int32    `protobuf:"varint,11,opt,name=participantNum,proto3" json:"participantNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEventReq) Reset()         { *m = AddEventReq{} }
func (m *AddEventReq) String() string { return proto.CompactTextString(m) }
func (*AddEventReq) ProtoMessage()    {}
func (*AddEventReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4314db4f6a3e016f, []int{6}
}

func (m *AddEventReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEventReq.Unmarshal(m, b)
}
func (m *AddEventReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEventReq.Marshal(b, m, deterministic)
}
func (m *AddEventReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEventReq.Merge(m, src)
}
func (m *AddEventReq) XXX_Size() int {
	return xxx_messageInfo_AddEventReq.Size(m)
}
func (m *AddEventReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEventReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddEventReq proto.InternalMessageInfo

func (m *AddEventReq) GetManageId() int64 {
	if m != nil {
		return m.ManageId
	}
	return 0
}

func (m *AddEventReq) GetEventTitle() string {
	if m != nil {
		return m.EventTitle
	}
	return ""
}

func (m *AddEventReq) GetEventDescription() string {
	if m != nil {
		return m.EventDescription
	}
	return ""
}

func (m *AddEventReq) GetEventTime() string {
	if m != nil {
		return m.EventTime
	}
	return ""
}

func (m *AddEventReq) GetEventNum() string {
	if m != nil {
		return m.EventNum
	}
	return ""
}

func (m *AddEventReq) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *AddEventReq) GetProblemRandom() bool {
	if m != nil {
		return m.ProblemRandom
	}
	return false
}

func (m *AddEventReq) GetOptionRandom() bool {
	if m != nil {
		return m.OptionRandom
	}
	return false
}

func (m *AddEventReq) GetAnswerTime() string {
	if m != nil {
		return m.AnswerTime
	}
	return ""
}

func (m *AddEventReq) GetCreditRule() string {
	if m != nil {
		return m.CreditRule
	}
	return ""
}

func (m *AddEventReq) GetParticipantNum() int32 {
	if m != nil {
		return m.ParticipantNum
	}
	return 0
}

type AddEventRsp struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	EventId              int64    `protobuf:"varint,2,opt,name=eventId,proto3" json:"eventId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEventRsp) Reset()         { *m = AddEventRsp{} }
func (m *AddEventRsp) String() string { return proto.CompactTextString(m) }
func (*AddEventRsp) ProtoMessage()    {}
func (*AddEventRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4314db4f6a3e016f, []int{7}
}

func (m *AddEventRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEventRsp.Unmarshal(m, b)
}
func (m *AddEventRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEventRsp.Marshal(b, m, deterministic)
}
func (m *AddEventRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEventRsp.Merge(m, src)
}
func (m *AddEventRsp) XXX_Size() int {
	return xxx_messageInfo_AddEventRsp.Size(m)
}
func (m *AddEventRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEventRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AddEventRsp proto.InternalMessageInfo

func (m *AddEventRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AddEventRsp) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func init() {
	proto.RegisterType((*EventIdReq)(nil), "EventIdReq")
	proto.RegisterType((*EventDetailMesssage)(nil), "EventDetailMesssage")
	proto.RegisterType((*EventShowMesssage)(nil), "EventShowMesssage")
	proto.RegisterType((*GetEventListReq)(nil), "GetEventListReq")
	proto.RegisterType((*EventMesssage)(nil), "EventMesssage")
	proto.RegisterType((*EventListRsp)(nil), "EventListRsp")
	proto.RegisterType((*AddEventReq)(nil), "AddEventReq")
	proto.RegisterType((*AddEventRsp)(nil), "AddEventRsp")
}

func init() { proto.RegisterFile("eventManage.proto", fileDescriptor_4314db4f6a3e016f) }

var fileDescriptor_4314db4f6a3e016f = []byte{
	// 716 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x4d, 0x4f, 0x1b, 0x3b,
	0x14, 0x65, 0xf2, 0x45, 0x72, 0x27, 0x01, 0x62, 0x10, 0xcf, 0x8a, 0x9e, 0x50, 0x34, 0x7a, 0x42,
	0xd1, 0x7b, 0x4f, 0xb3, 0xa0, 0x52, 0x57, 0x55, 0x25, 0x28, 0x08, 0x21, 0x15, 0x2a, 0x19, 0x58,
	0x75, 0x35, 0x64, 0x9c, 0xd4, 0xd5, 0x7c, 0x75, 0xc6, 0x29, 0xca, 0xba, 0x3f, 0xa1, 0x3f, 0xa6,
	0x3f, 0xad, 0xcb, 0x56, 0xbe, 0x9e, 0x0f, 0x4f, 0x08, 0xb4, 0x8b, 0xb6, 0xbb, 0x39, 0xe7, 0x5e,
	0xdb, 0xf7, 0x9e, 0x39, 0xbe, 0x86, 0x21, 0xff, 0xc8, 0x23, 0x79, 0xe9, 0x45, 0xde, 0x9c, 0xbb,
	0x49, 0x1a, 0xcb, 0xd8, 0x39, 0x04, 0x38, 0x53, 0xe4, 0x85, 0xcf, 0xf8, 0x07, 0x42, 0x61, 0x93,
	0x6b, 0x44, 0xad, 0xb1, 0x35, 0x69, 0xb2, 0x02, 0x3a, 0x9f, 0xda, 0xb0, 0x8b, 0x89, 0xa7, 0x5c,
	0x7a, 0x22, 0xb8, 0xe4, 0x59, 0x96, 0x79, 0x73, 0xfe, 0xf8, 0x0a, 0x72, 0x00, 0x80, 0x9f, 0x37,
	0x42, 0x06, 0x9c, 0x36, 0xc6, 0xd6, 0xa4, 0xc7, 0x0c, 0x86, 0xfc, 0x0d, 0x3d, 0x8d, 0x96, 0x09,
	0xa7, 0x4d, 0x0c, 0x57, 0x04, 0xf9, 0x17, 0x76, 0xb8, 0x3e, 0x2e, 0x9b, 0xa6, 0x22, 0x91, 0x22,
	0x8e, 0x68, 0x0b, 0x93, 0x1e, 0xf0, 0xe4, 0x10, 0xb6, 0x12, 0x2f, 0x95, 0x62, 0x2a, 0x12, 0x2f,
	0x92, 0x57, 0x8b, 0x90, 0xb6, 0xc7, 0xd6, 0xa4, 0xcd, 0x56, 0x58, 0x75, 0x62, 0x26, 0xbd, 0x54,
	0xde, 0x88, 0x90, 0xd3, 0x8e, 0x3e, 0xb1, 0x24, 0xb0, 0x93, 0xc8, 0xc7, 0xd8, 0x26, 0xc6, 0x0a,
	0xa8, 0xd6, 0x79, 0x51, 0x76, 0xcf, 0xd3, 0x53, 0x6f, 0x49, 0xbb, 0x7a, 0x5d, 0x49, 0x90, 0x31,
	0xd8, 0x99, 0x88, 0xe6, 0x01, 0xbf, 0x9e, 0xc6, 0x29, 0xa7, 0xbd, 0xb1, 0x35, 0xb1, 0x98, 0x49,
	0xa9, 0xf5, 0x33, 0x11, 0x04, 0x3a, 0x0e, 0x18, 0xaf, 0x08, 0xa5, 0xd3, 0xfb, 0x85, 0x3f, 0xcf,
	0x97, 0xdb, 0x18, 0x36, 0x18, 0xf2, 0x0f, 0x0c, 0xc2, 0x45, 0x20, 0x45, 0x52, 0x9c, 0xd0, 0xc7,
	0x94, 0x3a, 0xa9, 0xce, 0x90, 0xdc, 0x0b, 0x75, 0xc6, 0x40, 0x9f, 0x51, 0x12, 0xaa, 0xc6, 0x12,
	0xdc, 0x26, 0x74, 0x4b, 0xd7, 0x68, 0x50, 0x2a, 0x23, 0xe1, 0x69, 0x16, 0x47, 0x7a, 0x87, 0x6d,
	0x9d, 0x61, 0x50, 0xaa, 0x0e, 0x03, 0xde, 0x26, 0x74, 0x47, 0xd7, 0x51, 0x23, 0xc9, 0x3e, 0x74,
	0x74, 0xeb, 0x74, 0x88, 0x42, 0xe5, 0x88, 0x10, 0x68, 0xa9, 0x96, 0x29, 0x41, 0x16, 0xbf, 0xc9,
	0x1e, 0xb4, 0xb1, 0x4f, 0xba, 0x8b, 0xa4, 0x06, 0x64, 0x04, 0xdd, 0xa2, 0x35, 0xba, 0x87, 0x81,
	0x12, 0x3b, 0x5f, 0x1a, 0x30, 0x44, 0x17, 0x5e, 0xbf, 0x8b, 0xef, 0x7f, 0x81, 0x07, 0xd7, 0xb9,
	0xac, 0xf9, 0xd3, 0x2e, 0x6b, 0xfd, 0xd8, 0x65, 0xed, 0x27, 0x5c, 0xd6, 0xa9, 0xbb, 0xac, 0x52,
	0x6e, 0x73, 0xad, 0x72, 0xdd, 0x75, 0xca, 0xf5, 0x1e, 0x53, 0x0e, 0x56, 0x94, 0x7b, 0x0b, 0xdb,
	0xe7, 0x5c, 0xa2, 0x76, 0xaf, 0x45, 0x26, 0xd5, 0x65, 0xdf, 0x87, 0x4e, 0x3c, 0x9b, 0x65, 0x5c,
	0xa2, 0x6a, 0x6d, 0x96, 0x23, 0xb5, 0x79, 0x20, 0x42, 0x21, 0x51, 0xaf, 0x36, 0xd3, 0x00, 0x37,
	0xc7, 0xc1, 0x71, 0xe1, 0xa3, 0x44, 0x4d, 0x56, 0x62, 0xe7, 0xb3, 0x05, 0x03, 0xdc, 0xfa, 0x0f,
	0xff, 0x92, 0xda, 0x08, 0x69, 0xad, 0x8c, 0x10, 0xe7, 0x05, 0xf4, 0xab, 0x7e, 0xb3, 0x84, 0xfc,
	0x9f, 0x67, 0x2b, 0x4c, 0xad, 0x71, 0x73, 0x62, 0x1f, 0x6d, 0xb9, 0xb5, 0xb2, 0x59, 0x95, 0xe0,
	0x7c, 0x6b, 0x80, 0x7d, 0xec, 0xfb, 0x18, 0x57, 0x6a, 0x99, 0xfd, 0x5b, 0xf5, 0xfe, 0x7f, 0x4f,
	0x4f, 0xca, 0x22, 0xb5, 0x9e, 0x94, 0x49, 0x46, 0xd0, 0x45, 0x50, 0x0c, 0xb9, 0x1e, 0x2b, 0x71,
	0x5d, 0x8d, 0xce, 0xea, 0x40, 0x55, 0xd7, 0x37, 0x8d, 0xef, 0x02, 0x1e, 0x32, 0x2f, 0xf2, 0xe3,
	0x10, 0x5d, 0xd6, 0x65, 0x75, 0x92, 0x38, 0xd0, 0x8f, 0xb1, 0x8e, 0x3c, 0xa9, 0x8b, 0x49, 0x35,
	0x4e, 0x75, 0xab, 0xa7, 0x1f, 0x96, 0xa8, 0x1d, 0x68, 0x30, 0x2a, 0x3e, 0x4d, 0xb9, 0x2f, 0x24,
	0x5b, 0x94, 0x46, 0x34, 0x98, 0x35, 0x17, 0xc9, 0x5e, 0x77, 0x91, 0x9c, 0x63, 0xe3, 0x07, 0x64,
	0x89, 0xb2, 0x54, 0xc8, 0xf1, 0x37, 0xa1, 0xfe, 0x3d, 0x56, 0x40, 0xd3, 0x6c, 0x8d, 0x9a, 0xd9,
	0x8e, 0xbe, 0x5a, 0x60, 0x9f, 0x55, 0x6f, 0x1e, 0x79, 0x05, 0x07, 0xe6, 0x2d, 0x38, 0x59, 0x5e,
	0xe6, 0xbf, 0xf0, 0x38, 0xf2, 0xdf, 0xcc, 0x66, 0x99, 0x24, 0x3b, 0xee, 0xca, 0x35, 0x19, 0x0d,
	0x5c, 0xd3, 0x45, 0xce, 0x06, 0xf9, 0x0f, 0xeb, 0xba, 0xe2, 0xf7, 0xc8, 0x93, 0xbe, 0x6b, 0xd8,
	0x64, 0x64, 0x20, 0x4c, 0x7e, 0x0e, 0xc3, 0x62, 0xc3, 0x93, 0x65, 0xfe, 0xd2, 0x12, 0xdb, 0xad,
	0xde, 0xdc, 0x11, 0x71, 0x1f, 0x4c, 0x34, 0x67, 0x83, 0xbc, 0x84, 0xbf, 0xce, 0x79, 0xfe, 0xd8,
	0x3e, 0xb5, 0x7a, 0xcf, 0x5d, 0xf3, 0x2a, 0x3b, 0x1b, 0x77, 0x1d, 0x7c, 0xde, 0x9f, 0x7d, 0x0f,
	0x00, 0x00, 0xff, 0xff, 0xa1, 0x9d, 0x60, 0x2a, 0xf3, 0x07, 0x00, 0x00,
}
