// Code generated by protoc-gen-go. DO NOT EDIT.
// source: problemManage.proto

package problemManage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetProblemListReq struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	ManageId             int64    `protobuf:"varint,3,opt,name=manageId,proto3" json:"manageId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProblemListReq) Reset()         { *m = GetProblemListReq{} }
func (m *GetProblemListReq) String() string { return proto.CompactTextString(m) }
func (*GetProblemListReq) ProtoMessage()    {}
func (*GetProblemListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d2c35f53333d071, []int{0}
}

func (m *GetProblemListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProblemListReq.Unmarshal(m, b)
}
func (m *GetProblemListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProblemListReq.Marshal(b, m, deterministic)
}
func (m *GetProblemListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProblemListReq.Merge(m, src)
}
func (m *GetProblemListReq) XXX_Size() int {
	return xxx_messageInfo_GetProblemListReq.Size(m)
}
func (m *GetProblemListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProblemListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProblemListReq proto.InternalMessageInfo

func (m *GetProblemListReq) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetProblemListReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetProblemListReq) GetManageId() int64 {
	if m != nil {
		return m.ManageId
	}
	return 0
}

type ProblemMesssage struct {
	ProblemId            int64    `protobuf:"varint,1,opt,name=problemId,proto3" json:"problemId,omitempty"`
	ProblemContent       string   `protobuf:"bytes,2,opt,name=problemContent,proto3" json:"problemContent,omitempty"`
	ProblemOption        string   `protobuf:"bytes,3,opt,name=problemOption,proto3" json:"problemOption,omitempty"`
	ProblemAnswer        string   `protobuf:"bytes,4,opt,name=problemAnswer,proto3" json:"problemAnswer,omitempty"`
	ProblemClass         string   `protobuf:"bytes,5,opt,name=problemClass,proto3" json:"problemClass,omitempty"`
	ProblemType          int32    `protobuf:"varint,6,opt,name=problemType,proto3" json:"problemType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProblemMesssage) Reset()         { *m = ProblemMesssage{} }
func (m *ProblemMesssage) String() string { return proto.CompactTextString(m) }
func (*ProblemMesssage) ProtoMessage()    {}
func (*ProblemMesssage) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d2c35f53333d071, []int{1}
}

func (m *ProblemMesssage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemMesssage.Unmarshal(m, b)
}
func (m *ProblemMesssage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemMesssage.Marshal(b, m, deterministic)
}
func (m *ProblemMesssage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemMesssage.Merge(m, src)
}
func (m *ProblemMesssage) XXX_Size() int {
	return xxx_messageInfo_ProblemMesssage.Size(m)
}
func (m *ProblemMesssage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemMesssage.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemMesssage proto.InternalMessageInfo

func (m *ProblemMesssage) GetProblemId() int64 {
	if m != nil {
		return m.ProblemId
	}
	return 0
}

func (m *ProblemMesssage) GetProblemContent() string {
	if m != nil {
		return m.ProblemContent
	}
	return ""
}

func (m *ProblemMesssage) GetProblemOption() string {
	if m != nil {
		return m.ProblemOption
	}
	return ""
}

func (m *ProblemMesssage) GetProblemAnswer() string {
	if m != nil {
		return m.ProblemAnswer
	}
	return ""
}

func (m *ProblemMesssage) GetProblemClass() string {
	if m != nil {
		return m.ProblemClass
	}
	return ""
}

func (m *ProblemMesssage) GetProblemType() int32 {
	if m != nil {
		return m.ProblemType
	}
	return 0
}

type ProblemListRsp struct {
	ProblemList          []*ProblemMesssage `protobuf:"bytes,1,rep,name=problemList,proto3" json:"problemList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ProblemListRsp) Reset()         { *m = ProblemListRsp{} }
func (m *ProblemListRsp) String() string { return proto.CompactTextString(m) }
func (*ProblemListRsp) ProtoMessage()    {}
func (*ProblemListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d2c35f53333d071, []int{2}
}

func (m *ProblemListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemListRsp.Unmarshal(m, b)
}
func (m *ProblemListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemListRsp.Marshal(b, m, deterministic)
}
func (m *ProblemListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemListRsp.Merge(m, src)
}
func (m *ProblemListRsp) XXX_Size() int {
	return xxx_messageInfo_ProblemListRsp.Size(m)
}
func (m *ProblemListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemListRsp proto.InternalMessageInfo

func (m *ProblemListRsp) GetProblemList() []*ProblemMesssage {
	if m != nil {
		return m.ProblemList
	}
	return nil
}

func init() {
	proto.RegisterType((*GetProblemListReq)(nil), "GetProblemListReq")
	proto.RegisterType((*ProblemMesssage)(nil), "ProblemMesssage")
	proto.RegisterType((*ProblemListRsp)(nil), "ProblemListRsp")
}

func init() { proto.RegisterFile("problemManage.proto", fileDescriptor_4d2c35f53333d071) }

var fileDescriptor_4d2c35f53333d071 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0xad, 0xb5, 0xc5, 0xde, 0xb9, 0x4d, 0xaf, 0x22, 0x61, 0x28, 0x94, 0x22, 0xd2, 0xa7,
	0x3e, 0xd4, 0x5f, 0x30, 0x15, 0x65, 0xb0, 0xb1, 0x11, 0x04, 0x9f, 0x7c, 0xe8, 0x68, 0x3a, 0x0a,
	0x6d, 0x52, 0x9b, 0x80, 0xec, 0x27, 0xfb, 0x2f, 0xc4, 0x34, 0xce, 0x66, 0x7b, 0x3c, 0x5f, 0x4e,
	0xee, 0xbd, 0x9c, 0x03, 0x97, 0x4d, 0x2b, 0xd6, 0x15, 0xab, 0x17, 0x19, 0xcf, 0x36, 0x2c, 0x69,
	0x5a, 0xa1, 0x44, 0xf4, 0x01, 0x17, 0xaf, 0x4c, 0xad, 0xba, 0x97, 0x79, 0x29, 0x15, 0x65, 0x9f,
	0x78, 0x0d, 0xbe, 0x28, 0x0a, 0xc9, 0x14, 0x71, 0x42, 0x27, 0xf6, 0xa8, 0x51, 0x78, 0x05, 0x5e,
	0x55, 0xd6, 0xa5, 0x22, 0xc7, 0x1a, 0x77, 0x02, 0x27, 0x70, 0x5a, 0xeb, 0x91, 0xb3, 0x9c, 0xb8,
	0xa1, 0x13, 0xbb, 0x74, 0xa7, 0xa3, 0x6f, 0x07, 0xc6, 0x66, 0xf8, 0x82, 0x49, 0x29, 0xb3, 0x0d,
	0xc3, 0x1b, 0x08, 0xcc, 0x25, 0xb3, 0x5c, 0x2f, 0x70, 0xe9, 0x3f, 0xc0, 0x7b, 0x18, 0x19, 0xf1,
	0x24, 0xb8, 0x62, 0xbc, 0x5b, 0x16, 0xd0, 0x3d, 0x8a, 0x77, 0x30, 0x34, 0x64, 0xd9, 0xa8, 0x52,
	0x70, 0xbd, 0x3a, 0xa0, 0x36, 0xec, 0xb9, 0xa6, 0x5c, 0x7e, 0xb1, 0x96, 0x9c, 0x58, 0xae, 0x0e,
	0x62, 0x04, 0x67, 0x7f, 0xd3, 0xab, 0x4c, 0x4a, 0xe2, 0x69, 0x93, 0xc5, 0x30, 0x84, 0x81, 0xd1,
	0x6f, 0xdb, 0x86, 0x11, 0x5f, 0x27, 0xd0, 0x47, 0xd1, 0x33, 0x8c, 0xfa, 0x39, 0xca, 0x06, 0xd3,
	0xdd, 0x9f, 0x5f, 0x42, 0x9c, 0xd0, 0x8d, 0x07, 0xe9, 0x79, 0xb2, 0x17, 0x08, 0xed, 0x9b, 0xd2,
	0x77, 0x18, 0xae, 0xfa, 0x3d, 0xe1, 0x0b, 0xdc, 0xda, 0x0d, 0x3d, 0x6e, 0x97, 0x45, 0x21, 0xd5,
	0x94, 0xe7, 0x73, 0x9d, 0x3f, 0x26, 0x07, 0x0d, 0x4e, 0xc6, 0x89, 0x7d, 0x4a, 0x74, 0xb4, 0xf6,
	0x75, 0xe1, 0x0f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x21, 0x67, 0xfb, 0x07, 0x02, 0x00,
	0x00,
}
