// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userManage.proto

package userManage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserMesssage struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LoginName            string   `protobuf:"bytes,2,opt,name=login_name,json=loginName,proto3" json:"login_name,omitempty"`
	Pwd                  string   `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	JobNumber            string   `protobuf:"bytes,6,opt,name=job_number,json=jobNumber,proto3" json:"job_number,omitempty"`
	Permission           int32    `protobuf:"varint,7,opt,name=permission,proto3" json:"permission,omitempty"`
	Gender               int32    `protobuf:"varint,8,opt,name=gender,proto3" json:"gender,omitempty"`
	Deleted              bool     `protobuf:"varint,9,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMesssage) Reset()         { *m = UserMesssage{} }
func (m *UserMesssage) String() string { return proto.CompactTextString(m) }
func (*UserMesssage) ProtoMessage()    {}
func (*UserMesssage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22129ec94f3fdfd, []int{0}
}

func (m *UserMesssage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMesssage.Unmarshal(m, b)
}
func (m *UserMesssage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMesssage.Marshal(b, m, deterministic)
}
func (m *UserMesssage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMesssage.Merge(m, src)
}
func (m *UserMesssage) XXX_Size() int {
	return xxx_messageInfo_UserMesssage.Size(m)
}
func (m *UserMesssage) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMesssage.DiscardUnknown(m)
}

var xxx_messageInfo_UserMesssage proto.InternalMessageInfo

func (m *UserMesssage) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserMesssage) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *UserMesssage) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *UserMesssage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserMesssage) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UserMesssage) GetJobNumber() string {
	if m != nil {
		return m.JobNumber
	}
	return ""
}

func (m *UserMesssage) GetPermission() int32 {
	if m != nil {
		return m.Permission
	}
	return 0
}

func (m *UserMesssage) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *UserMesssage) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type UpdatePwdReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OldPwd               string   `protobuf:"bytes,2,opt,name=oldPwd,proto3" json:"oldPwd,omitempty"`
	NewPwd               string   `protobuf:"bytes,3,opt,name=newPwd,proto3" json:"newPwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePwdReq) Reset()         { *m = UpdatePwdReq{} }
func (m *UpdatePwdReq) String() string { return proto.CompactTextString(m) }
func (*UpdatePwdReq) ProtoMessage()    {}
func (*UpdatePwdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22129ec94f3fdfd, []int{1}
}

func (m *UpdatePwdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePwdReq.Unmarshal(m, b)
}
func (m *UpdatePwdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePwdReq.Marshal(b, m, deterministic)
}
func (m *UpdatePwdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePwdReq.Merge(m, src)
}
func (m *UpdatePwdReq) XXX_Size() int {
	return xxx_messageInfo_UpdatePwdReq.Size(m)
}
func (m *UpdatePwdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePwdReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePwdReq proto.InternalMessageInfo

func (m *UpdatePwdReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpdatePwdReq) GetOldPwd() string {
	if m != nil {
		return m.OldPwd
	}
	return ""
}

func (m *UpdatePwdReq) GetNewPwd() string {
	if m != nil {
		return m.NewPwd
	}
	return ""
}

type UpdatePwdRsp struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePwdRsp) Reset()         { *m = UpdatePwdRsp{} }
func (m *UpdatePwdRsp) String() string { return proto.CompactTextString(m) }
func (*UpdatePwdRsp) ProtoMessage()    {}
func (*UpdatePwdRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22129ec94f3fdfd, []int{2}
}

func (m *UpdatePwdRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePwdRsp.Unmarshal(m, b)
}
func (m *UpdatePwdRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePwdRsp.Marshal(b, m, deterministic)
}
func (m *UpdatePwdRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePwdRsp.Merge(m, src)
}
func (m *UpdatePwdRsp) XXX_Size() int {
	return xxx_messageInfo_UpdatePwdRsp.Size(m)
}
func (m *UpdatePwdRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePwdRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePwdRsp proto.InternalMessageInfo

func (m *UpdatePwdRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type LoginReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22129ec94f3fdfd, []int{3}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginReq) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type LoginRsp struct {
	LoginFlag            bool     `protobuf:"varint,1,opt,name=loginFlag,proto3" json:"loginFlag,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Permission           int32    `protobuf:"varint,3,opt,name=permission,proto3" json:"permission,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRsp) Reset()         { *m = LoginRsp{} }
func (m *LoginRsp) String() string { return proto.CompactTextString(m) }
func (*LoginRsp) ProtoMessage()    {}
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22129ec94f3fdfd, []int{4}
}

func (m *LoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRsp.Unmarshal(m, b)
}
func (m *LoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRsp.Marshal(b, m, deterministic)
}
func (m *LoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRsp.Merge(m, src)
}
func (m *LoginRsp) XXX_Size() int {
	return xxx_messageInfo_LoginRsp.Size(m)
}
func (m *LoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRsp proto.InternalMessageInfo

func (m *LoginRsp) GetLoginFlag() bool {
	if m != nil {
		return m.LoginFlag
	}
	return false
}

func (m *LoginRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LoginRsp) GetPermission() int32 {
	if m != nil {
		return m.Permission
	}
	return 0
}

func (m *LoginRsp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetUserListReq struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	ManageId             int64    `protobuf:"varint,3,opt,name=manageId,proto3" json:"manageId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserListReq) Reset()         { *m = GetUserListReq{} }
func (m *GetUserListReq) String() string { return proto.CompactTextString(m) }
func (*GetUserListReq) ProtoMessage()    {}
func (*GetUserListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22129ec94f3fdfd, []int{5}
}

func (m *GetUserListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserListReq.Unmarshal(m, b)
}
func (m *GetUserListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserListReq.Marshal(b, m, deterministic)
}
func (m *GetUserListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserListReq.Merge(m, src)
}
func (m *GetUserListReq) XXX_Size() int {
	return xxx_messageInfo_GetUserListReq.Size(m)
}
func (m *GetUserListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserListReq proto.InternalMessageInfo

func (m *GetUserListReq) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetUserListReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetUserListReq) GetManageId() int64 {
	if m != nil {
		return m.ManageId
	}
	return 0
}

type UserListRsp struct {
	UserList             []*UserMesssage `protobuf:"bytes,1,rep,name=userList,proto3" json:"userList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserListRsp) Reset()         { *m = UserListRsp{} }
func (m *UserListRsp) String() string { return proto.CompactTextString(m) }
func (*UserListRsp) ProtoMessage()    {}
func (*UserListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22129ec94f3fdfd, []int{6}
}

func (m *UserListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListRsp.Unmarshal(m, b)
}
func (m *UserListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListRsp.Marshal(b, m, deterministic)
}
func (m *UserListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListRsp.Merge(m, src)
}
func (m *UserListRsp) XXX_Size() int {
	return xxx_messageInfo_UserListRsp.Size(m)
}
func (m *UserListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UserListRsp proto.InternalMessageInfo

func (m *UserListRsp) GetUserList() []*UserMesssage {
	if m != nil {
		return m.UserList
	}
	return nil
}

type ChangeUserReq struct {
	ChangeId             int64    `protobuf:"varint,1,opt,name=changeId,proto3" json:"changeId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LoginName            string   `protobuf:"bytes,3,opt,name=loginName,proto3" json:"loginName,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	JobNumber            string   `protobuf:"bytes,5,opt,name=jobNumber,proto3" json:"jobNumber,omitempty"`
	Gender               int32    `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeUserReq) Reset()         { *m = ChangeUserReq{} }
func (m *ChangeUserReq) String() string { return proto.CompactTextString(m) }
func (*ChangeUserReq) ProtoMessage()    {}
func (*ChangeUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22129ec94f3fdfd, []int{7}
}

func (m *ChangeUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeUserReq.Unmarshal(m, b)
}
func (m *ChangeUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeUserReq.Marshal(b, m, deterministic)
}
func (m *ChangeUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeUserReq.Merge(m, src)
}
func (m *ChangeUserReq) XXX_Size() int {
	return xxx_messageInfo_ChangeUserReq.Size(m)
}
func (m *ChangeUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeUserReq proto.InternalMessageInfo

func (m *ChangeUserReq) GetChangeId() int64 {
	if m != nil {
		return m.ChangeId
	}
	return 0
}

func (m *ChangeUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChangeUserReq) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *ChangeUserReq) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *ChangeUserReq) GetJobNumber() string {
	if m != nil {
		return m.JobNumber
	}
	return ""
}

func (m *ChangeUserReq) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

type ChangeUserRsp struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeUserRsp) Reset()         { *m = ChangeUserRsp{} }
func (m *ChangeUserRsp) String() string { return proto.CompactTextString(m) }
func (*ChangeUserRsp) ProtoMessage()    {}
func (*ChangeUserRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22129ec94f3fdfd, []int{8}
}

func (m *ChangeUserRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeUserRsp.Unmarshal(m, b)
}
func (m *ChangeUserRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeUserRsp.Marshal(b, m, deterministic)
}
func (m *ChangeUserRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeUserRsp.Merge(m, src)
}
func (m *ChangeUserRsp) XXX_Size() int {
	return xxx_messageInfo_ChangeUserRsp.Size(m)
}
func (m *ChangeUserRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeUserRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeUserRsp proto.InternalMessageInfo

func (m *ChangeUserRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChangeUserRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type AddUserReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LoginName            string   `protobuf:"bytes,2,opt,name=loginName,proto3" json:"loginName,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	JobNumber            string   `protobuf:"bytes,4,opt,name=jobNumber,proto3" json:"jobNumber,omitempty"`
	Gender               int32    `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserReq) Reset()         { *m = AddUserReq{} }
func (m *AddUserReq) String() string { return proto.CompactTextString(m) }
func (*AddUserReq) ProtoMessage()    {}
func (*AddUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22129ec94f3fdfd, []int{9}
}

func (m *AddUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserReq.Unmarshal(m, b)
}
func (m *AddUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserReq.Marshal(b, m, deterministic)
}
func (m *AddUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserReq.Merge(m, src)
}
func (m *AddUserReq) XXX_Size() int {
	return xxx_messageInfo_AddUserReq.Size(m)
}
func (m *AddUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserReq proto.InternalMessageInfo

func (m *AddUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddUserReq) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *AddUserReq) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *AddUserReq) GetJobNumber() string {
	if m != nil {
		return m.JobNumber
	}
	return ""
}

func (m *AddUserReq) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

type AddUserRsp struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserRsp) Reset()         { *m = AddUserRsp{} }
func (m *AddUserRsp) String() string { return proto.CompactTextString(m) }
func (*AddUserRsp) ProtoMessage()    {}
func (*AddUserRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22129ec94f3fdfd, []int{10}
}

func (m *AddUserRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRsp.Unmarshal(m, b)
}
func (m *AddUserRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRsp.Marshal(b, m, deterministic)
}
func (m *AddUserRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRsp.Merge(m, src)
}
func (m *AddUserRsp) XXX_Size() int {
	return xxx_messageInfo_AddUserRsp.Size(m)
}
func (m *AddUserRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRsp proto.InternalMessageInfo

func (m *AddUserRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AddUserRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type DeleteUserReq struct {
	DeleteId             int64    `protobuf:"varint,1,opt,name=deleteId,proto3" json:"deleteId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserReq) Reset()         { *m = DeleteUserReq{} }
func (m *DeleteUserReq) String() string { return proto.CompactTextString(m) }
func (*DeleteUserReq) ProtoMessage()    {}
func (*DeleteUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22129ec94f3fdfd, []int{11}
}

func (m *DeleteUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserReq.Unmarshal(m, b)
}
func (m *DeleteUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserReq.Marshal(b, m, deterministic)
}
func (m *DeleteUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserReq.Merge(m, src)
}
func (m *DeleteUserReq) XXX_Size() int {
	return xxx_messageInfo_DeleteUserReq.Size(m)
}
func (m *DeleteUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserReq proto.InternalMessageInfo

func (m *DeleteUserReq) GetDeleteId() int64 {
	if m != nil {
		return m.DeleteId
	}
	return 0
}

type DeleteUserRsp struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRsp) Reset()         { *m = DeleteUserRsp{} }
func (m *DeleteUserRsp) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRsp) ProtoMessage()    {}
func (*DeleteUserRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22129ec94f3fdfd, []int{12}
}

func (m *DeleteUserRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRsp.Unmarshal(m, b)
}
func (m *DeleteUserRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRsp.Marshal(b, m, deterministic)
}
func (m *DeleteUserRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRsp.Merge(m, src)
}
func (m *DeleteUserRsp) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRsp.Size(m)
}
func (m *DeleteUserRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRsp proto.InternalMessageInfo

func (m *DeleteUserRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DeleteUserRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetUserByIdReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByIdReq) Reset()         { *m = GetUserByIdReq{} }
func (m *GetUserByIdReq) String() string { return proto.CompactTextString(m) }
func (*GetUserByIdReq) ProtoMessage()    {}
func (*GetUserByIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22129ec94f3fdfd, []int{13}
}

func (m *GetUserByIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIdReq.Unmarshal(m, b)
}
func (m *GetUserByIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIdReq.Marshal(b, m, deterministic)
}
func (m *GetUserByIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIdReq.Merge(m, src)
}
func (m *GetUserByIdReq) XXX_Size() int {
	return xxx_messageInfo_GetUserByIdReq.Size(m)
}
func (m *GetUserByIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIdReq proto.InternalMessageInfo

func (m *GetUserByIdReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*UserMesssage)(nil), "UserMesssage")
	proto.RegisterType((*UpdatePwdReq)(nil), "UpdatePwdReq")
	proto.RegisterType((*UpdatePwdRsp)(nil), "UpdatePwdRsp")
	proto.RegisterType((*LoginReq)(nil), "LoginReq")
	proto.RegisterType((*LoginRsp)(nil), "LoginRsp")
	proto.RegisterType((*GetUserListReq)(nil), "GetUserListReq")
	proto.RegisterType((*UserListRsp)(nil), "UserListRsp")
	proto.RegisterType((*ChangeUserReq)(nil), "ChangeUserReq")
	proto.RegisterType((*ChangeUserRsp)(nil), "ChangeUserRsp")
	proto.RegisterType((*AddUserReq)(nil), "AddUserReq")
	proto.RegisterType((*AddUserRsp)(nil), "AddUserRsp")
	proto.RegisterType((*DeleteUserReq)(nil), "DeleteUserReq")
	proto.RegisterType((*DeleteUserRsp)(nil), "DeleteUserRsp")
	proto.RegisterType((*GetUserByIdReq)(nil), "GetUserByIdReq")
}

func init() { proto.RegisterFile("userManage.proto", fileDescriptor_f22129ec94f3fdfd) }

var fileDescriptor_f22129ec94f3fdfd = []byte{
	// 661 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0xde, 0x24, 0x4d, 0x7f, 0x4e, 0x7f, 0x5c, 0x06, 0x91, 0x10, 0x56, 0x8d, 0x03, 0x42, 0x44,
	0x88, 0x50, 0x6f, 0xf6, 0x46, 0xa1, 0xab, 0x28, 0x85, 0xba, 0x96, 0x40, 0xbd, 0xf0, 0x66, 0x49,
	0x9d, 0x69, 0x36, 0x6b, 0xf3, 0x63, 0x27, 0x6b, 0xd9, 0x17, 0xf1, 0x4d, 0x7c, 0x1c, 0x9f, 0xc3,
	0x5b, 0x99, 0xc9, 0x4c, 0x32, 0x41, 0xba, 0x0b, 0x7b, 0x97, 0xef, 0xcc, 0xcc, 0x39, 0xf3, 0x7d,
	0xe7, 0x9b, 0x13, 0x38, 0xbe, 0x66, 0x74, 0xf7, 0x29, 0xca, 0xa2, 0x98, 0x06, 0xc5, 0x2e, 0x2f,
	0x73, 0xfc, 0xd7, 0x80, 0xd1, 0x8a, 0x07, 0x29, 0x63, 0x2c, 0x8a, 0x29, 0x9a, 0x80, 0x99, 0x10,
	0xc7, 0xf0, 0x0c, 0xdf, 0x0a, 0xcd, 0x84, 0xa0, 0xc7, 0x00, 0xdb, 0x3c, 0x4e, 0xb2, 0x8b, 0x2c,
	0x4a, 0xa9, 0x63, 0x7a, 0x86, 0x3f, 0x08, 0x07, 0x22, 0x72, 0x1e, 0xa5, 0x14, 0x1d, 0x83, 0x55,
	0xec, 0x89, 0x63, 0x89, 0x38, 0xff, 0x44, 0x08, 0x3a, 0x62, 0x6b, 0x47, 0x84, 0xc4, 0x37, 0x7a,
	0x06, 0xa3, 0xe2, 0x32, 0xcf, 0xe8, 0x45, 0x76, 0x9d, 0xae, 0xe9, 0xce, 0xb1, 0xc5, 0xda, 0x50,
	0xc4, 0xce, 0x45, 0x88, 0xd7, 0xb9, 0xca, 0xd7, 0x6a, 0x43, 0xb7, 0xaa, 0x73, 0x95, 0xaf, 0xe5,
	0xf2, 0x13, 0x80, 0x82, 0xee, 0xd2, 0x84, 0xb1, 0x24, 0xcf, 0x9c, 0x9e, 0x67, 0xf8, 0x76, 0xa8,
	0x45, 0xd0, 0x23, 0xe8, 0xc6, 0x34, 0x23, 0x74, 0xe7, 0xf4, 0xc5, 0x9a, 0x44, 0xc8, 0x81, 0x1e,
	0xa1, 0x5b, 0x5a, 0x52, 0xe2, 0x0c, 0x3c, 0xc3, 0xef, 0x87, 0x0a, 0xe2, 0x2f, 0x30, 0x5a, 0x15,
	0x24, 0x2a, 0xe9, 0x72, 0x4f, 0x42, 0xfa, 0x83, 0x67, 0xe0, 0xea, 0xcc, 0x15, 0x79, 0x89, 0x78,
	0x3c, 0xdf, 0x92, 0xe5, 0x9e, 0x48, 0xf2, 0x12, 0xf1, 0x78, 0x46, 0xf7, 0xcb, 0x9a, 0xbc, 0x44,
	0xd8, 0xd7, 0xf3, 0xb2, 0x82, 0xdf, 0x20, 0xa5, 0x42, 0x5b, 0x91, 0x78, 0x10, 0x2a, 0x88, 0x4f,
	0xa1, 0xbf, 0xe0, 0x42, 0xf2, 0xea, 0x2e, 0xf4, 0x79, 0x3d, 0xa1, 0x5c, 0xb5, 0xad, 0xc6, 0x4a,
	0x63, 0xb3, 0xd6, 0x18, 0xff, 0x54, 0x27, 0x59, 0x81, 0x4e, 0xa0, 0x6a, 0xc7, 0x87, 0x6d, 0x14,
	0x8b, 0xa3, 0xfd, 0xb0, 0x09, 0x68, 0xac, 0xcc, 0x16, 0xab, 0xb6, 0x9e, 0xd6, 0x7f, 0x7a, 0x3e,
	0x04, 0xbb, 0xcc, 0xbf, 0xd3, 0x4c, 0xb6, 0xb1, 0x02, 0xf8, 0x2b, 0x4c, 0x3e, 0xd2, 0x92, 0xfb,
	0x65, 0x91, 0xb0, 0x52, 0xaa, 0x96, 0x6f, 0x36, 0x8c, 0x96, 0xa2, 0xb4, 0x1d, 0x4a, 0xc4, 0xcf,
	0x6f, 0x93, 0x34, 0x29, 0x45, 0x59, 0x3b, 0xac, 0x00, 0x67, 0x99, 0x0a, 0xf7, 0xcd, 0x2b, 0xd5,
	0xac, 0xb0, 0xc6, 0xf8, 0x14, 0x86, 0x75, 0x62, 0x56, 0xa0, 0x17, 0x95, 0x20, 0x1c, 0x3a, 0x86,
	0x67, 0xf9, 0xc3, 0xe9, 0x38, 0xd0, 0x8d, 0x1a, 0xd6, 0xcb, 0xf8, 0xb7, 0x01, 0xe3, 0x77, 0x97,
	0x51, 0x16, 0x53, 0xbe, 0x41, 0xaa, 0xf9, 0x4d, 0x04, 0xea, 0x6e, 0xd6, 0xb8, 0xf6, 0xa7, 0xa9,
	0xf9, 0x53, 0x69, 0xc8, 0x2d, 0x2d, 0xdb, 0xa9, 0x79, 0xdc, 0x03, 0xdd, 0xa9, 0x52, 0x91, 0x96,
	0x79, 0x4f, 0xa0, 0xb1, 0xaa, 0x34, 0xb7, 0xe6, 0xdd, 0xc6, 0x9b, 0x5d, 0xdd, 0x9b, 0x78, 0xd6,
	0xba, 0xf6, 0x6d, 0x56, 0x39, 0xd4, 0x46, 0xfc, 0xcb, 0x00, 0x98, 0x11, 0xa2, 0x78, 0x2b, 0x6e,
	0xc6, 0x21, 0x6e, 0xe6, 0x1d, 0xdc, 0xac, 0x3b, 0xb8, 0x75, 0x0e, 0x73, 0xb3, 0x5b, 0xdc, 0xde,
	0x36, 0xf7, 0xba, 0x17, 0xb1, 0x97, 0x30, 0x7e, 0x2f, 0x1e, 0xaa, 0xd6, 0xd2, 0xea, 0xe5, 0x36,
	0x2d, 0x55, 0x98, 0x0b, 0xa9, 0x6d, 0xbe, 0x57, 0x3d, 0xbf, 0x76, 0xf6, 0xd9, 0xcd, 0xfc, 0xb6,
	0x79, 0x30, 0xfd, 0x63, 0x02, 0xac, 0xea, 0x31, 0x8a, 0xde, 0x80, 0xab, 0x3d, 0x89, 0xb3, 0x9b,
	0xcf, 0x9b, 0x0d, 0x2b, 0x67, 0x19, 0x59, 0x08, 0xc3, 0x3f, 0x08, 0xda, 0xef, 0xc5, 0x1d, 0x05,
	0x9a, 0xc9, 0xf1, 0x11, 0x9a, 0xc2, 0xa4, 0x9a, 0x16, 0xaa, 0x34, 0x9a, 0x04, 0x2d, 0x2f, 0xbb,
	0x2d, 0x2c, 0xce, 0x3c, 0x87, 0x9e, 0xd4, 0x16, 0x0d, 0x83, 0xa6, 0xfb, 0x6e, 0x03, 0x54, 0xea,
	0x46, 0x15, 0x99, 0xba, 0xa5, 0xa9, 0xdb, 0xc2, 0xe2, 0xcc, 0x2b, 0x18, 0x6a, 0x32, 0x34, 0xd7,
	0x97, 0xa2, 0xb8, 0xed, 0x37, 0x88, 0x8f, 0xd0, 0x53, 0xb0, 0xc5, 0x24, 0x42, 0x83, 0x40, 0xcd,
	0x32, 0x57, 0x7d, 0xca, 0x8c, 0xe3, 0x86, 0x20, 0x9f, 0x9b, 0xe3, 0x40, 0x1f, 0xbb, 0xae, 0x0e,
	0xf9, 0x81, 0x75, 0x57, 0xfc, 0x98, 0x5e, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x67, 0x46, 0x1a,
	0x9f, 0xac, 0x06, 0x00, 0x00,
}
