// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userManage.proto

package userManage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetUserListReq struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	ManageId             int64    `protobuf:"varint,3,opt,name=manageId,proto3" json:"manageId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserListReq) Reset()         { *m = GetUserListReq{} }
func (m *GetUserListReq) String() string { return proto.CompactTextString(m) }
func (*GetUserListReq) ProtoMessage()    {}
func (*GetUserListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22129ec94f3fdfd, []int{0}
}

func (m *GetUserListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserListReq.Unmarshal(m, b)
}
func (m *GetUserListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserListReq.Marshal(b, m, deterministic)
}
func (m *GetUserListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserListReq.Merge(m, src)
}
func (m *GetUserListReq) XXX_Size() int {
	return xxx_messageInfo_GetUserListReq.Size(m)
}
func (m *GetUserListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserListReq proto.InternalMessageInfo

func (m *GetUserListReq) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetUserListReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetUserListReq) GetManageId() int64 {
	if m != nil {
		return m.ManageId
	}
	return 0
}

type UserMesssage struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LoginName            string   `protobuf:"bytes,2,opt,name=loginName,proto3" json:"loginName,omitempty"`
	Pwd                  string   `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,5,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	JobNumber            string   `protobuf:"bytes,6,opt,name=jobNumber,proto3" json:"jobNumber,omitempty"`
	Permission           int32    `protobuf:"varint,7,opt,name=permission,proto3" json:"permission,omitempty"`
	Gender               int32    `protobuf:"varint,8,opt,name=gender,proto3" json:"gender,omitempty"`
	Deleted              bool     `protobuf:"varint,9,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMesssage) Reset()         { *m = UserMesssage{} }
func (m *UserMesssage) String() string { return proto.CompactTextString(m) }
func (*UserMesssage) ProtoMessage()    {}
func (*UserMesssage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22129ec94f3fdfd, []int{1}
}

func (m *UserMesssage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMesssage.Unmarshal(m, b)
}
func (m *UserMesssage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMesssage.Marshal(b, m, deterministic)
}
func (m *UserMesssage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMesssage.Merge(m, src)
}
func (m *UserMesssage) XXX_Size() int {
	return xxx_messageInfo_UserMesssage.Size(m)
}
func (m *UserMesssage) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMesssage.DiscardUnknown(m)
}

var xxx_messageInfo_UserMesssage proto.InternalMessageInfo

func (m *UserMesssage) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserMesssage) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *UserMesssage) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *UserMesssage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserMesssage) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UserMesssage) GetJobNumber() string {
	if m != nil {
		return m.JobNumber
	}
	return ""
}

func (m *UserMesssage) GetPermission() int32 {
	if m != nil {
		return m.Permission
	}
	return 0
}

func (m *UserMesssage) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *UserMesssage) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type UserListRsp struct {
	UserList             []*UserMesssage `protobuf:"bytes,1,rep,name=userList,proto3" json:"userList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserListRsp) Reset()         { *m = UserListRsp{} }
func (m *UserListRsp) String() string { return proto.CompactTextString(m) }
func (*UserListRsp) ProtoMessage()    {}
func (*UserListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22129ec94f3fdfd, []int{2}
}

func (m *UserListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListRsp.Unmarshal(m, b)
}
func (m *UserListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListRsp.Marshal(b, m, deterministic)
}
func (m *UserListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListRsp.Merge(m, src)
}
func (m *UserListRsp) XXX_Size() int {
	return xxx_messageInfo_UserListRsp.Size(m)
}
func (m *UserListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UserListRsp proto.InternalMessageInfo

func (m *UserListRsp) GetUserList() []*UserMesssage {
	if m != nil {
		return m.UserList
	}
	return nil
}

func init() {
	proto.RegisterType((*GetUserListReq)(nil), "GetUserListReq")
	proto.RegisterType((*UserMesssage)(nil), "UserMesssage")
	proto.RegisterType((*UserListRsp)(nil), "UserListRsp")
}

func init() { proto.RegisterFile("userManage.proto", fileDescriptor_f22129ec94f3fdfd) }

var fileDescriptor_f22129ec94f3fdfd = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x4f, 0x4b, 0xeb, 0x40,
	0x14, 0xc5, 0x5f, 0x9a, 0xfe, 0x49, 0x6e, 0xfb, 0xfa, 0xca, 0xe5, 0x21, 0x43, 0x11, 0x09, 0x59,
	0xc5, 0x4d, 0x16, 0x75, 0xe3, 0xc6, 0x85, 0x6e, 0x44, 0x6c, 0x2b, 0x0c, 0x74, 0xe3, 0x2e, 0x65,
	0x6e, 0xe2, 0x48, 0x33, 0x13, 0x33, 0x53, 0xc4, 0xef, 0xed, 0x07, 0x90, 0x4c, 0x6a, 0x8c, 0xbb,
	0x7b, 0x7e, 0x77, 0x38, 0x97, 0x39, 0x07, 0x16, 0x47, 0x43, 0xf5, 0x26, 0x53, 0x59, 0x41, 0x69,
	0x55, 0x6b, 0xab, 0xe3, 0x67, 0x98, 0xdf, 0x93, 0xdd, 0x19, 0xaa, 0xd7, 0xd2, 0x58, 0x4e, 0x6f,
	0x78, 0x06, 0x63, 0x9d, 0xe7, 0x86, 0x2c, 0xf3, 0x22, 0x2f, 0x19, 0xf1, 0x93, 0xc2, 0xff, 0x30,
	0x3a, 0xc8, 0x52, 0x5a, 0x36, 0x70, 0xb8, 0x15, 0xb8, 0x84, 0xa0, 0x74, 0x7e, 0x0f, 0x82, 0xf9,
	0x91, 0x97, 0xf8, 0xbc, 0xd3, 0xf1, 0xa7, 0x07, 0xb3, 0xc6, 0x79, 0x43, 0xc6, 0x98, 0xac, 0x20,
	0x9c, 0xc3, 0x40, 0x0a, 0x67, 0xeb, 0xf3, 0x81, 0x14, 0x78, 0x0e, 0xe1, 0x41, 0x17, 0x52, 0x6d,
	0xb3, 0x92, 0x9c, 0x6d, 0xc8, 0x7f, 0x00, 0x2e, 0xc0, 0xaf, 0xde, 0x5b, 0xd7, 0x90, 0x37, 0x23,
	0x22, 0x0c, 0x55, 0xf3, 0x74, 0xe8, 0x90, 0x9b, 0x31, 0x82, 0x69, 0xf5, 0xa2, 0x15, 0x6d, 0x8f,
	0xe5, 0x9e, 0x6a, 0x36, 0x72, 0xab, 0x3e, 0x6a, 0xae, 0xbc, 0xea, 0xfd, 0x69, 0x3f, 0x6e, 0xaf,
	0x74, 0x00, 0x2f, 0x00, 0x2a, 0xaa, 0x4b, 0x69, 0x8c, 0xd4, 0x8a, 0x4d, 0xdc, 0xdf, 0x7a, 0xa4,
	0x89, 0xa3, 0x20, 0x25, 0xa8, 0x66, 0x41, 0x1b, 0x47, 0xab, 0x90, 0xc1, 0x44, 0xd0, 0x81, 0x2c,
	0x09, 0x16, 0x46, 0x5e, 0x12, 0xf0, 0x6f, 0x19, 0x5f, 0xc3, 0xb4, 0xcb, 0xd3, 0x54, 0x78, 0x09,
	0xc1, 0xf1, 0x24, 0x99, 0x17, 0xf9, 0xc9, 0x74, 0xf5, 0x37, 0xed, 0xa7, 0xc2, 0xbb, 0xf5, 0xea,
	0x11, 0x60, 0xd7, 0x15, 0x84, 0x37, 0xb0, 0xec, 0x55, 0x73, 0xf7, 0xf1, 0x94, 0xe7, 0xc6, 0xde,
	0x2a, 0xb1, 0x76, 0xc1, 0xff, 0x4b, 0x7f, 0xf7, 0xb6, 0x9c, 0xa5, 0xbd, 0xab, 0xf1, 0x9f, 0xfd,
	0xd8, 0x15, 0x7c, 0xf5, 0x15, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x84, 0x39, 0x4e, 0xf4, 0x01, 0x00,
	0x00,
}
