// Code generated by protoc-gen-go. DO NOT EDIT.
// source: creditManage.proto

package creditManage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateTeamCreditReq struct {
	TeamId               int64    `protobuf:"varint,1,opt,name=teamId,proto3" json:"teamId,omitempty"`
	ChangeCredit         float64  `protobuf:"fixed64,2,opt,name=changeCredit,proto3" json:"changeCredit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTeamCreditReq) Reset()         { *m = UpdateTeamCreditReq{} }
func (m *UpdateTeamCreditReq) String() string { return proto.CompactTextString(m) }
func (*UpdateTeamCreditReq) ProtoMessage()    {}
func (*UpdateTeamCreditReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_58158031a537f5d8, []int{0}
}

func (m *UpdateTeamCreditReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTeamCreditReq.Unmarshal(m, b)
}
func (m *UpdateTeamCreditReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTeamCreditReq.Marshal(b, m, deterministic)
}
func (m *UpdateTeamCreditReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTeamCreditReq.Merge(m, src)
}
func (m *UpdateTeamCreditReq) XXX_Size() int {
	return xxx_messageInfo_UpdateTeamCreditReq.Size(m)
}
func (m *UpdateTeamCreditReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTeamCreditReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTeamCreditReq proto.InternalMessageInfo

func (m *UpdateTeamCreditReq) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *UpdateTeamCreditReq) GetChangeCredit() float64 {
	if m != nil {
		return m.ChangeCredit
	}
	return 0
}

type UpdatePCreditReq struct {
	PaticipantId         int64    `protobuf:"varint,1,opt,name=paticipantId,proto3" json:"paticipantId,omitempty"`
	ChangeCredit         float64  `protobuf:"fixed64,2,opt,name=changeCredit,proto3" json:"changeCredit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePCreditReq) Reset()         { *m = UpdatePCreditReq{} }
func (m *UpdatePCreditReq) String() string { return proto.CompactTextString(m) }
func (*UpdatePCreditReq) ProtoMessage()    {}
func (*UpdatePCreditReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_58158031a537f5d8, []int{1}
}

func (m *UpdatePCreditReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePCreditReq.Unmarshal(m, b)
}
func (m *UpdatePCreditReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePCreditReq.Marshal(b, m, deterministic)
}
func (m *UpdatePCreditReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePCreditReq.Merge(m, src)
}
func (m *UpdatePCreditReq) XXX_Size() int {
	return xxx_messageInfo_UpdatePCreditReq.Size(m)
}
func (m *UpdatePCreditReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePCreditReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePCreditReq proto.InternalMessageInfo

func (m *UpdatePCreditReq) GetPaticipantId() int64 {
	if m != nil {
		return m.PaticipantId
	}
	return 0
}

func (m *UpdatePCreditReq) GetChangeCredit() float64 {
	if m != nil {
		return m.ChangeCredit
	}
	return 0
}

type AllRightReq struct {
	TeamId               int64    `protobuf:"varint,1,opt,name=teamId,proto3" json:"teamId,omitempty"`
	NowDate              string   `protobuf:"bytes,2,opt,name=nowDate,proto3" json:"nowDate,omitempty"`
	ParticipantNum       int32    `protobuf:"varint,3,opt,name=participantNum,proto3" json:"participantNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllRightReq) Reset()         { *m = AllRightReq{} }
func (m *AllRightReq) String() string { return proto.CompactTextString(m) }
func (*AllRightReq) ProtoMessage()    {}
func (*AllRightReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_58158031a537f5d8, []int{2}
}

func (m *AllRightReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllRightReq.Unmarshal(m, b)
}
func (m *AllRightReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllRightReq.Marshal(b, m, deterministic)
}
func (m *AllRightReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllRightReq.Merge(m, src)
}
func (m *AllRightReq) XXX_Size() int {
	return xxx_messageInfo_AllRightReq.Size(m)
}
func (m *AllRightReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AllRightReq.DiscardUnknown(m)
}

var xxx_messageInfo_AllRightReq proto.InternalMessageInfo

func (m *AllRightReq) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *AllRightReq) GetNowDate() string {
	if m != nil {
		return m.NowDate
	}
	return ""
}

func (m *AllRightReq) GetParticipantNum() int32 {
	if m != nil {
		return m.ParticipantNum
	}
	return 0
}

type AllRightRsp struct {
	AllRightFlag         bool     `protobuf:"varint,1,opt,name=allRightFlag,proto3" json:"allRightFlag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllRightRsp) Reset()         { *m = AllRightRsp{} }
func (m *AllRightRsp) String() string { return proto.CompactTextString(m) }
func (*AllRightRsp) ProtoMessage()    {}
func (*AllRightRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_58158031a537f5d8, []int{3}
}

func (m *AllRightRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllRightRsp.Unmarshal(m, b)
}
func (m *AllRightRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllRightRsp.Marshal(b, m, deterministic)
}
func (m *AllRightRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllRightRsp.Merge(m, src)
}
func (m *AllRightRsp) XXX_Size() int {
	return xxx_messageInfo_AllRightRsp.Size(m)
}
func (m *AllRightRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AllRightRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AllRightRsp proto.InternalMessageInfo

func (m *AllRightRsp) GetAllRightFlag() bool {
	if m != nil {
		return m.AllRightFlag
	}
	return false
}

type TeamIdReq struct {
	TeamId               int64    `protobuf:"varint,1,opt,name=teamId,proto3" json:"teamId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamIdReq) Reset()         { *m = TeamIdReq{} }
func (m *TeamIdReq) String() string { return proto.CompactTextString(m) }
func (*TeamIdReq) ProtoMessage()    {}
func (*TeamIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_58158031a537f5d8, []int{4}
}

func (m *TeamIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamIdReq.Unmarshal(m, b)
}
func (m *TeamIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamIdReq.Marshal(b, m, deterministic)
}
func (m *TeamIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamIdReq.Merge(m, src)
}
func (m *TeamIdReq) XXX_Size() int {
	return xxx_messageInfo_TeamIdReq.Size(m)
}
func (m *TeamIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_TeamIdReq proto.InternalMessageInfo

func (m *TeamIdReq) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

type TeamEventIdReq struct {
	TeamId               int64    `protobuf:"varint,1,opt,name=teamId,proto3" json:"teamId,omitempty"`
	EventId              int64    `protobuf:"varint,2,opt,name=eventId,proto3" json:"eventId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamEventIdReq) Reset()         { *m = TeamEventIdReq{} }
func (m *TeamEventIdReq) String() string { return proto.CompactTextString(m) }
func (*TeamEventIdReq) ProtoMessage()    {}
func (*TeamEventIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_58158031a537f5d8, []int{5}
}

func (m *TeamEventIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamEventIdReq.Unmarshal(m, b)
}
func (m *TeamEventIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamEventIdReq.Marshal(b, m, deterministic)
}
func (m *TeamEventIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamEventIdReq.Merge(m, src)
}
func (m *TeamEventIdReq) XXX_Size() int {
	return xxx_messageInfo_TeamEventIdReq.Size(m)
}
func (m *TeamEventIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamEventIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_TeamEventIdReq proto.InternalMessageInfo

func (m *TeamEventIdReq) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *TeamEventIdReq) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

type UserEventIdReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	EventId              int64    `protobuf:"varint,2,opt,name=eventId,proto3" json:"eventId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserEventIdReq) Reset()         { *m = UserEventIdReq{} }
func (m *UserEventIdReq) String() string { return proto.CompactTextString(m) }
func (*UserEventIdReq) ProtoMessage()    {}
func (*UserEventIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_58158031a537f5d8, []int{6}
}

func (m *UserEventIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEventIdReq.Unmarshal(m, b)
}
func (m *UserEventIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEventIdReq.Marshal(b, m, deterministic)
}
func (m *UserEventIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEventIdReq.Merge(m, src)
}
func (m *UserEventIdReq) XXX_Size() int {
	return xxx_messageInfo_UserEventIdReq.Size(m)
}
func (m *UserEventIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEventIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserEventIdReq proto.InternalMessageInfo

func (m *UserEventIdReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserEventIdReq) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

type CreditRsp struct {
	Credit               float64  `protobuf:"fixed64,1,opt,name=credit,proto3" json:"credit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreditRsp) Reset()         { *m = CreditRsp{} }
func (m *CreditRsp) String() string { return proto.CompactTextString(m) }
func (*CreditRsp) ProtoMessage()    {}
func (*CreditRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_58158031a537f5d8, []int{7}
}

func (m *CreditRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreditRsp.Unmarshal(m, b)
}
func (m *CreditRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreditRsp.Marshal(b, m, deterministic)
}
func (m *CreditRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreditRsp.Merge(m, src)
}
func (m *CreditRsp) XXX_Size() int {
	return xxx_messageInfo_CreditRsp.Size(m)
}
func (m *CreditRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreditRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CreditRsp proto.InternalMessageInfo

func (m *CreditRsp) GetCredit() float64 {
	if m != nil {
		return m.Credit
	}
	return 0
}

type CreditLog struct {
	CreditLogId          int64    `protobuf:"varint,1,opt,name=creditLogId,proto3" json:"creditLogId,omitempty"`
	EventId              int64    `protobuf:"varint,2,opt,name=eventId,proto3" json:"eventId,omitempty"`
	TeamId               int64    `protobuf:"varint,3,opt,name=teamId,proto3" json:"teamId,omitempty"`
	ParticipantId        int64    `protobuf:"varint,4,opt,name=participantId,proto3" json:"participantId,omitempty"`
	ChangeReason         string   `protobuf:"bytes,5,opt,name=changeReason,proto3" json:"changeReason,omitempty"`
	ChangeValue          float32  `protobuf:"fixed32,6,opt,name=changeValue,proto3" json:"changeValue,omitempty"`
	ChangeTime           string   `protobuf:"bytes,7,opt,name=changeTime,proto3" json:"changeTime,omitempty"`
	ChangeType           int32    `protobuf:"varint,8,opt,name=changeType,proto3" json:"changeType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreditLog) Reset()         { *m = CreditLog{} }
func (m *CreditLog) String() string { return proto.CompactTextString(m) }
func (*CreditLog) ProtoMessage()    {}
func (*CreditLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_58158031a537f5d8, []int{8}
}

func (m *CreditLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreditLog.Unmarshal(m, b)
}
func (m *CreditLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreditLog.Marshal(b, m, deterministic)
}
func (m *CreditLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreditLog.Merge(m, src)
}
func (m *CreditLog) XXX_Size() int {
	return xxx_messageInfo_CreditLog.Size(m)
}
func (m *CreditLog) XXX_DiscardUnknown() {
	xxx_messageInfo_CreditLog.DiscardUnknown(m)
}

var xxx_messageInfo_CreditLog proto.InternalMessageInfo

func (m *CreditLog) GetCreditLogId() int64 {
	if m != nil {
		return m.CreditLogId
	}
	return 0
}

func (m *CreditLog) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *CreditLog) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *CreditLog) GetParticipantId() int64 {
	if m != nil {
		return m.ParticipantId
	}
	return 0
}

func (m *CreditLog) GetChangeReason() string {
	if m != nil {
		return m.ChangeReason
	}
	return ""
}

func (m *CreditLog) GetChangeValue() float32 {
	if m != nil {
		return m.ChangeValue
	}
	return 0
}

func (m *CreditLog) GetChangeTime() string {
	if m != nil {
		return m.ChangeTime
	}
	return ""
}

func (m *CreditLog) GetChangeType() int32 {
	if m != nil {
		return m.ChangeType
	}
	return 0
}

type CreditLogListRsp struct {
	CreditLogList        []*CreditLog `protobuf:"bytes,1,rep,name=creditLogList,proto3" json:"creditLogList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreditLogListRsp) Reset()         { *m = CreditLogListRsp{} }
func (m *CreditLogListRsp) String() string { return proto.CompactTextString(m) }
func (*CreditLogListRsp) ProtoMessage()    {}
func (*CreditLogListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_58158031a537f5d8, []int{9}
}

func (m *CreditLogListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreditLogListRsp.Unmarshal(m, b)
}
func (m *CreditLogListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreditLogListRsp.Marshal(b, m, deterministic)
}
func (m *CreditLogListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreditLogListRsp.Merge(m, src)
}
func (m *CreditLogListRsp) XXX_Size() int {
	return xxx_messageInfo_CreditLogListRsp.Size(m)
}
func (m *CreditLogListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreditLogListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CreditLogListRsp proto.InternalMessageInfo

func (m *CreditLogListRsp) GetCreditLogList() []*CreditLog {
	if m != nil {
		return m.CreditLogList
	}
	return nil
}

type AddCreditLogRsp struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	CreditLogId          int64    `protobuf:"varint,2,opt,name=creditLogId,proto3" json:"creditLogId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCreditLogRsp) Reset()         { *m = AddCreditLogRsp{} }
func (m *AddCreditLogRsp) String() string { return proto.CompactTextString(m) }
func (*AddCreditLogRsp) ProtoMessage()    {}
func (*AddCreditLogRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_58158031a537f5d8, []int{10}
}

func (m *AddCreditLogRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCreditLogRsp.Unmarshal(m, b)
}
func (m *AddCreditLogRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCreditLogRsp.Marshal(b, m, deterministic)
}
func (m *AddCreditLogRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCreditLogRsp.Merge(m, src)
}
func (m *AddCreditLogRsp) XXX_Size() int {
	return xxx_messageInfo_AddCreditLogRsp.Size(m)
}
func (m *AddCreditLogRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCreditLogRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AddCreditLogRsp proto.InternalMessageInfo

func (m *AddCreditLogRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AddCreditLogRsp) GetCreditLogId() int64 {
	if m != nil {
		return m.CreditLogId
	}
	return 0
}

func init() {
	proto.RegisterType((*UpdateTeamCreditReq)(nil), "UpdateTeamCreditReq")
	proto.RegisterType((*UpdatePCreditReq)(nil), "UpdatePCreditReq")
	proto.RegisterType((*AllRightReq)(nil), "AllRightReq")
	proto.RegisterType((*AllRightRsp)(nil), "AllRightRsp")
	proto.RegisterType((*TeamIdReq)(nil), "TeamIdReq")
	proto.RegisterType((*TeamEventIdReq)(nil), "TeamEventIdReq")
	proto.RegisterType((*UserEventIdReq)(nil), "UserEventIdReq")
	proto.RegisterType((*CreditRsp)(nil), "CreditRsp")
	proto.RegisterType((*CreditLog)(nil), "CreditLog")
	proto.RegisterType((*CreditLogListRsp)(nil), "CreditLogListRsp")
	proto.RegisterType((*AddCreditLogRsp)(nil), "AddCreditLogRsp")
}

func init() { proto.RegisterFile("creditManage.proto", fileDescriptor_58158031a537f5d8) }

var fileDescriptor_58158031a537f5d8 = []byte{
	// 547 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x63, 0x9a, 0x36, 0x93, 0xa4, 0x49, 0x97, 0x02, 0x56, 0x0e, 0xc8, 0xda, 0x22, 0x94,
	0x93, 0x55, 0x8a, 0x00, 0x89, 0x5b, 0x3f, 0x20, 0xaa, 0xd4, 0xa0, 0xb2, 0x4a, 0x41, 0xe2, 0xb6,
	0x8d, 0x47, 0x8e, 0xa5, 0xf8, 0x03, 0xef, 0x06, 0xd4, 0x3b, 0x37, 0xfe, 0x34, 0xf2, 0xfa, 0x6b,
	0xd7, 0x40, 0xe0, 0xf8, 0xde, 0xce, 0xbc, 0x99, 0x79, 0x1e, 0x0f, 0x90, 0x65, 0x86, 0x7e, 0x28,
	0xe7, 0x3c, 0xe6, 0x01, 0x7a, 0x69, 0x96, 0xc8, 0x84, 0x7e, 0x84, 0x87, 0xb7, 0xa9, 0xcf, 0x25,
	0x2e, 0x90, 0x47, 0x17, 0xea, 0x9d, 0xe1, 0x57, 0xf2, 0x18, 0xba, 0x12, 0x79, 0x74, 0xe5, 0x3b,
	0x96, 0x6b, 0x4d, 0x6d, 0x56, 0x22, 0x42, 0x61, 0xb0, 0x5c, 0xf1, 0x38, 0xc0, 0x22, 0xd4, 0xe9,
	0xb8, 0xd6, 0xd4, 0x62, 0x06, 0x47, 0xbf, 0xc0, 0xb8, 0x90, 0xbc, 0x69, 0xf4, 0x28, 0x0c, 0x52,
	0x2e, 0xc3, 0x65, 0x98, 0xf2, 0x58, 0xd6, 0xaa, 0x06, 0xf7, 0x5f, 0xda, 0x01, 0xf4, 0xcf, 0xd6,
	0x6b, 0x16, 0x06, 0xab, 0xad, 0x6d, 0x3a, 0xb0, 0x17, 0x27, 0xdf, 0x2f, 0xb9, 0x44, 0xa5, 0xd2,
	0x63, 0x15, 0x24, 0xcf, 0xe1, 0x20, 0xe5, 0x59, 0x55, 0xf5, 0xc3, 0x26, 0x72, 0x6c, 0xd7, 0x9a,
	0xee, 0xb2, 0x16, 0x4b, 0x5f, 0x68, 0x85, 0x44, 0x9a, 0xf7, 0xc6, 0x4b, 0xf8, 0x7e, 0xcd, 0x03,
	0x55, 0x6e, 0x9f, 0x19, 0x1c, 0x3d, 0x86, 0xde, 0x42, 0x95, 0xdf, 0xd2, 0x19, 0x3d, 0x87, 0x83,
	0x3c, 0xe8, 0xdd, 0x37, 0xcc, 0x67, 0xfe, 0xc7, 0x0c, 0x58, 0x44, 0xa9, 0x19, 0x6c, 0x56, 0xc1,
	0x5c, 0xe3, 0x56, 0x60, 0x66, 0x6a, 0x6c, 0x04, 0x66, 0x8d, 0x46, 0x81, 0xb6, 0x68, 0x1c, 0x43,
	0xaf, 0xfc, 0x3a, 0x22, 0xcd, 0xd3, 0x8b, 0xd5, 0x50, 0xe9, 0x16, 0x2b, 0x11, 0xfd, 0xd9, 0xa9,
	0xa2, 0xae, 0x93, 0x80, 0xb8, 0xd0, 0x5f, 0x56, 0xa0, 0xae, 0xa4, 0x53, 0x7f, 0x2f, 0xa7, 0x0d,
	0x69, 0x1b, 0x43, 0x3e, 0x83, 0xa1, 0x66, 0xfc, 0x95, 0xef, 0x3c, 0x50, 0xcf, 0x26, 0xd9, 0x6c,
	0x06, 0x43, 0x2e, 0x92, 0xd8, 0xd9, 0x55, 0xdf, 0xd4, 0xe0, 0x54, 0x77, 0x0a, 0x7f, 0xe2, 0xeb,
	0x0d, 0x3a, 0x5d, 0xd7, 0x9a, 0x76, 0x98, 0x4e, 0x91, 0xa7, 0x00, 0x05, 0x5c, 0x84, 0x11, 0x3a,
	0x7b, 0x4a, 0x43, 0x63, 0xb4, 0xf7, 0xfb, 0x14, 0x9d, 0x7d, 0xb5, 0x16, 0x1a, 0x43, 0x2f, 0x61,
	0x5c, 0x9b, 0x71, 0x1d, 0x0a, 0xe5, 0xdc, 0x09, 0x0c, 0x97, 0x3a, 0xe7, 0x58, 0xae, 0x3d, 0xed,
	0x9f, 0x82, 0x57, 0x47, 0x32, 0x33, 0x80, 0xce, 0x61, 0x74, 0xe6, 0xfb, 0xcd, 0xb3, 0x48, 0x73,
	0xdb, 0x22, 0x14, 0x82, 0x07, 0xa8, 0x4c, 0xed, 0xb1, 0x0a, 0xb6, 0x2d, 0xef, 0xfc, 0x66, 0xf9,
	0xe9, 0x0f, 0x1b, 0x06, 0x17, 0xda, 0x6f, 0x4d, 0x3c, 0x18, 0xce, 0x50, 0x36, 0x7f, 0x33, 0x19,
	0x79, 0xe6, 0xc2, 0x4d, 0xaa, 0xe6, 0x98, 0x48, 0xe9, 0x0e, 0x39, 0x81, 0xd1, 0x0c, 0xe5, 0x0d,
	0x66, 0x22, 0x89, 0xeb, 0x0c, 0x73, 0xbd, 0x5a, 0x19, 0x6f, 0xe0, 0x68, 0x86, 0xb2, 0x9e, 0xe0,
	0xfc, 0xbe, 0xd8, 0x7a, 0x02, 0x5e, 0xbd, 0xfe, 0x93, 0x43, 0xaf, 0x6d, 0x15, 0xdd, 0x21, 0x1e,
	0x0c, 0xf4, 0xd1, 0x89, 0xe6, 0xd2, 0x64, 0xec, 0xb5, 0x5c, 0xa1, 0x3b, 0xe4, 0x15, 0x3c, 0xfa,
	0xbc, 0x42, 0xb9, 0xc2, 0x6c, 0x8e, 0xd1, 0x1d, 0x66, 0xd5, 0x0f, 0x49, 0x06, 0x9e, 0x76, 0x04,
	0x26, 0x1a, 0x52, 0x69, 0xaf, 0xab, 0xfb, 0xa3, 0x99, 0x70, 0xe4, 0xfd, 0xe1, 0xca, 0xb5, 0xe6,
	0x7a, 0x0b, 0x4f, 0xca, 0xbb, 0xd5, 0x2c, 0x5f, 0x99, 0x7e, 0xe8, 0xb5, 0x2f, 0x9a, 0x99, 0x7b,
	0xd7, 0x55, 0xd7, 0xf4, 0xe5, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x88, 0xcb, 0x46, 0x74, 0x63,
	0x05, 0x00, 0x00,
}
