// Code generated by protoc-gen-go. DO NOT EDIT.
// source: participantManage.proto

package answerManage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ParticipantMember struct {
	LeaderId             int64    `protobuf:"varint,1,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	MemberId             []int64  `protobuf:"varint,2,rep,packed,name=memberId,proto3" json:"memberId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParticipantMember) Reset()         { *m = ParticipantMember{} }
func (m *ParticipantMember) String() string { return proto.CompactTextString(m) }
func (*ParticipantMember) ProtoMessage()    {}
func (*ParticipantMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_df3ac8eeb97eee1b, []int{0}
}

func (m *ParticipantMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParticipantMember.Unmarshal(m, b)
}
func (m *ParticipantMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParticipantMember.Marshal(b, m, deterministic)
}
func (m *ParticipantMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParticipantMember.Merge(m, src)
}
func (m *ParticipantMember) XXX_Size() int {
	return xxx_messageInfo_ParticipantMember.Size(m)
}
func (m *ParticipantMember) XXX_DiscardUnknown() {
	xxx_messageInfo_ParticipantMember.DiscardUnknown(m)
}

var xxx_messageInfo_ParticipantMember proto.InternalMessageInfo

func (m *ParticipantMember) GetLeaderId() int64 {
	if m != nil {
		return m.LeaderId
	}
	return 0
}

func (m *ParticipantMember) GetMemberId() []int64 {
	if m != nil {
		return m.MemberId
	}
	return nil
}

type EPInsertReq struct {
	EventId               int64                `protobuf:"varint,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	ParticipantMemberList []*ParticipantMember `protobuf:"bytes,2,rep,name=participantMemberList,proto3" json:"participantMemberList,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}             `json:"-"`
	XXX_unrecognized      []byte               `json:"-"`
	XXX_sizecache         int32                `json:"-"`
}

func (m *EPInsertReq) Reset()         { *m = EPInsertReq{} }
func (m *EPInsertReq) String() string { return proto.CompactTextString(m) }
func (*EPInsertReq) ProtoMessage()    {}
func (*EPInsertReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_df3ac8eeb97eee1b, []int{1}
}

func (m *EPInsertReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EPInsertReq.Unmarshal(m, b)
}
func (m *EPInsertReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EPInsertReq.Marshal(b, m, deterministic)
}
func (m *EPInsertReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EPInsertReq.Merge(m, src)
}
func (m *EPInsertReq) XXX_Size() int {
	return xxx_messageInfo_EPInsertReq.Size(m)
}
func (m *EPInsertReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EPInsertReq.DiscardUnknown(m)
}

var xxx_messageInfo_EPInsertReq proto.InternalMessageInfo

func (m *EPInsertReq) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *EPInsertReq) GetParticipantMemberList() []*ParticipantMember {
	if m != nil {
		return m.ParticipantMemberList
	}
	return nil
}

type EPInsertRsp struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EPInsertRsp) Reset()         { *m = EPInsertRsp{} }
func (m *EPInsertRsp) String() string { return proto.CompactTextString(m) }
func (*EPInsertRsp) ProtoMessage()    {}
func (*EPInsertRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_df3ac8eeb97eee1b, []int{2}
}

func (m *EPInsertRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EPInsertRsp.Unmarshal(m, b)
}
func (m *EPInsertRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EPInsertRsp.Marshal(b, m, deterministic)
}
func (m *EPInsertRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EPInsertRsp.Merge(m, src)
}
func (m *EPInsertRsp) XXX_Size() int {
	return xxx_messageInfo_EPInsertRsp.Size(m)
}
func (m *EPInsertRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_EPInsertRsp.DiscardUnknown(m)
}

var xxx_messageInfo_EPInsertRsp proto.InternalMessageInfo

func (m *EPInsertRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetPListByUserIdReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPListByUserIdReq) Reset()         { *m = GetPListByUserIdReq{} }
func (m *GetPListByUserIdReq) String() string { return proto.CompactTextString(m) }
func (*GetPListByUserIdReq) ProtoMessage()    {}
func (*GetPListByUserIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_df3ac8eeb97eee1b, []int{3}
}

func (m *GetPListByUserIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPListByUserIdReq.Unmarshal(m, b)
}
func (m *GetPListByUserIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPListByUserIdReq.Marshal(b, m, deterministic)
}
func (m *GetPListByUserIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPListByUserIdReq.Merge(m, src)
}
func (m *GetPListByUserIdReq) XXX_Size() int {
	return xxx_messageInfo_GetPListByUserIdReq.Size(m)
}
func (m *GetPListByUserIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPListByUserIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetPListByUserIdReq proto.InternalMessageInfo

func (m *GetPListByUserIdReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type PEMessage struct {
	ParticipantId        int64    `protobuf:"varint,1,opt,name=participantId,proto3" json:"participantId,omitempty"`
	ReferEventId         int64    `protobuf:"varint,2,opt,name=referEventId,proto3" json:"referEventId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PEMessage) Reset()         { *m = PEMessage{} }
func (m *PEMessage) String() string { return proto.CompactTextString(m) }
func (*PEMessage) ProtoMessage()    {}
func (*PEMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_df3ac8eeb97eee1b, []int{4}
}

func (m *PEMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PEMessage.Unmarshal(m, b)
}
func (m *PEMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PEMessage.Marshal(b, m, deterministic)
}
func (m *PEMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PEMessage.Merge(m, src)
}
func (m *PEMessage) XXX_Size() int {
	return xxx_messageInfo_PEMessage.Size(m)
}
func (m *PEMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PEMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PEMessage proto.InternalMessageInfo

func (m *PEMessage) GetParticipantId() int64 {
	if m != nil {
		return m.ParticipantId
	}
	return 0
}

func (m *PEMessage) GetReferEventId() int64 {
	if m != nil {
		return m.ReferEventId
	}
	return 0
}

type PEMessageList struct {
	PEList               []*PEMessage `protobuf:"bytes,1,rep,name=PEList,proto3" json:"PEList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PEMessageList) Reset()         { *m = PEMessageList{} }
func (m *PEMessageList) String() string { return proto.CompactTextString(m) }
func (*PEMessageList) ProtoMessage()    {}
func (*PEMessageList) Descriptor() ([]byte, []int) {
	return fileDescriptor_df3ac8eeb97eee1b, []int{5}
}

func (m *PEMessageList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PEMessageList.Unmarshal(m, b)
}
func (m *PEMessageList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PEMessageList.Marshal(b, m, deterministic)
}
func (m *PEMessageList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PEMessageList.Merge(m, src)
}
func (m *PEMessageList) XXX_Size() int {
	return xxx_messageInfo_PEMessageList.Size(m)
}
func (m *PEMessageList) XXX_DiscardUnknown() {
	xxx_messageInfo_PEMessageList.DiscardUnknown(m)
}

var xxx_messageInfo_PEMessageList proto.InternalMessageInfo

func (m *PEMessageList) GetPEList() []*PEMessage {
	if m != nil {
		return m.PEList
	}
	return nil
}

type PUserEventIdReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	EventId              int64    `protobuf:"varint,2,opt,name=eventId,proto3" json:"eventId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PUserEventIdReq) Reset()         { *m = PUserEventIdReq{} }
func (m *PUserEventIdReq) String() string { return proto.CompactTextString(m) }
func (*PUserEventIdReq) ProtoMessage()    {}
func (*PUserEventIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_df3ac8eeb97eee1b, []int{6}
}

func (m *PUserEventIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PUserEventIdReq.Unmarshal(m, b)
}
func (m *PUserEventIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PUserEventIdReq.Marshal(b, m, deterministic)
}
func (m *PUserEventIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PUserEventIdReq.Merge(m, src)
}
func (m *PUserEventIdReq) XXX_Size() int {
	return xxx_messageInfo_PUserEventIdReq.Size(m)
}
func (m *PUserEventIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PUserEventIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_PUserEventIdReq proto.InternalMessageInfo

func (m *PUserEventIdReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PUserEventIdReq) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

type ParticipantMessage struct {
	ParticipantId        int64    `protobuf:"varint,1,opt,name=participantId,proto3" json:"participantId,omitempty"`
	EventId              int64    `protobuf:"varint,2,opt,name=eventId,proto3" json:"eventId,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	TeamId               int64    `protobuf:"varint,4,opt,name=teamId,proto3" json:"teamId,omitempty"`
	Credit               float64  `protobuf:"fixed64,5,opt,name=credit,proto3" json:"credit,omitempty"`
	Leader               bool     `protobuf:"varint,6,opt,name=leader,proto3" json:"leader,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParticipantMessage) Reset()         { *m = ParticipantMessage{} }
func (m *ParticipantMessage) String() string { return proto.CompactTextString(m) }
func (*ParticipantMessage) ProtoMessage()    {}
func (*ParticipantMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_df3ac8eeb97eee1b, []int{7}
}

func (m *ParticipantMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParticipantMessage.Unmarshal(m, b)
}
func (m *ParticipantMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParticipantMessage.Marshal(b, m, deterministic)
}
func (m *ParticipantMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParticipantMessage.Merge(m, src)
}
func (m *ParticipantMessage) XXX_Size() int {
	return xxx_messageInfo_ParticipantMessage.Size(m)
}
func (m *ParticipantMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ParticipantMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ParticipantMessage proto.InternalMessageInfo

func (m *ParticipantMessage) GetParticipantId() int64 {
	if m != nil {
		return m.ParticipantId
	}
	return 0
}

func (m *ParticipantMessage) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *ParticipantMessage) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ParticipantMessage) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *ParticipantMessage) GetCredit() float64 {
	if m != nil {
		return m.Credit
	}
	return 0
}

func (m *ParticipantMessage) GetLeader() bool {
	if m != nil {
		return m.Leader
	}
	return false
}

func init() {
	proto.RegisterType((*ParticipantMember)(nil), "participantMember")
	proto.RegisterType((*EPInsertReq)(nil), "EPInsertReq")
	proto.RegisterType((*EPInsertRsp)(nil), "EPInsertRsp")
	proto.RegisterType((*GetPListByUserIdReq)(nil), "GetPListByUserIdReq")
	proto.RegisterType((*PEMessage)(nil), "PEMessage")
	proto.RegisterType((*PEMessageList)(nil), "PEMessageList")
	proto.RegisterType((*PUserEventIdReq)(nil), "PUserEventIdReq")
	proto.RegisterType((*ParticipantMessage)(nil), "ParticipantMessage")
}

func init() { proto.RegisterFile("participantManage.proto", fileDescriptor_df3ac8eeb97eee1b) }

var fileDescriptor_df3ac8eeb97eee1b = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xdb, 0x8e, 0xda, 0x30,
	0x10, 0xc5, 0xd0, 0xa6, 0x30, 0x40, 0x5b, 0x4c, 0x4b, 0xa3, 0xa8, 0x0f, 0x91, 0x55, 0xa9, 0xbc,
	0xd4, 0x0f, 0x20, 0xf5, 0xbd, 0x97, 0x88, 0x46, 0x2d, 0x52, 0x14, 0x89, 0x0f, 0x08, 0x64, 0x8a,
	0x22, 0x35, 0x21, 0xd8, 0x6e, 0xa5, 0xfe, 0xd7, 0x7e, 0xcd, 0x7e, 0xcd, 0xca, 0x4e, 0xc8, 0x3a,
	0xc0, 0xae, 0xb4, 0x8f, 0x67, 0xce, 0x5c, 0xce, 0x8c, 0x8f, 0xe1, 0x5d, 0x99, 0x08, 0x95, 0xed,
	0xb2, 0x32, 0x29, 0xd4, 0x3a, 0x29, 0x92, 0x3d, 0xf2, 0x52, 0x1c, 0xd4, 0x81, 0xfd, 0x84, 0x89,
	0x4d, 0x61, 0xbe, 0x45, 0x41, 0x3d, 0xe8, 0xff, 0xc1, 0x24, 0x45, 0x11, 0xa6, 0x2e, 0xf1, 0xc9,
	0xbc, 0x17, 0x37, 0x58, 0x73, 0xb9, 0xc9, 0x0a, 0x53, 0xb7, 0xeb, 0xf7, 0x34, 0x77, 0xc2, 0xec,
	0x08, 0xc3, 0x20, 0x0a, 0x0b, 0x89, 0x42, 0xc5, 0x78, 0xa4, 0x2e, 0xbc, 0xc0, 0x7f, 0x58, 0xa8,
	0xa6, 0xcb, 0x09, 0xd2, 0x1f, 0xf0, 0xf6, 0x62, 0xea, 0xaf, 0x4c, 0x2a, 0xd3, 0x71, 0xb8, 0xa0,
	0xfc, 0x82, 0x8d, 0xaf, 0x17, 0xb0, 0x8f, 0xd6, 0x48, 0x59, 0xea, 0x91, 0x39, 0x4a, 0x99, 0xec,
	0xd1, 0x8c, 0x1c, 0xc4, 0x27, 0xc8, 0x3e, 0xc1, 0x74, 0x85, 0x2a, 0xd2, 0x45, 0x5f, 0xff, 0x6f,
	0xa4, 0xd6, 0xab, 0x35, 0xce, 0xc0, 0xf9, 0x2b, 0xad, 0x45, 0x6b, 0xc4, 0x36, 0x30, 0x88, 0x82,
	0x75, 0x55, 0x4b, 0x3f, 0xc0, 0xd8, 0x9a, 0xde, 0xe4, 0xb6, 0x83, 0x94, 0xc1, 0x48, 0xe0, 0x6f,
	0x14, 0x41, 0xbd, 0x73, 0xd7, 0x24, 0xb5, 0x62, 0x6c, 0x09, 0xe3, 0xa6, 0xad, 0x96, 0x42, 0x19,
	0x38, 0x51, 0x60, 0x56, 0x27, 0x66, 0x75, 0xe0, 0x0d, 0x1f, 0xd7, 0x0c, 0xfb, 0x06, 0xaf, 0x22,
	0xad, 0xb8, 0x6e, 0xf2, 0x88, 0x6c, 0xfb, 0xe4, 0xdd, 0xd6, 0xc9, 0xd9, 0x0d, 0x01, 0x1a, 0xd9,
	0x27, 0x7c, 0xca, 0x6a, 0x0f, 0xb6, 0xb5, 0x84, 0xf4, 0x5a, 0x42, 0x66, 0xe0, 0x28, 0x4c, 0xf2,
	0x30, 0x75, 0x9f, 0x55, 0xf1, 0x0a, 0xe9, 0xf8, 0x4e, 0x60, 0x9a, 0x29, 0xf7, 0xb9, 0x4f, 0xe6,
	0x24, 0xae, 0x91, 0x8e, 0x57, 0x16, 0x73, 0x1d, 0x9f, 0xcc, 0xfb, 0x71, 0x8d, 0x16, 0xb7, 0x04,
	0x26, 0xd1, 0xb9, 0x77, 0xe9, 0x67, 0x98, 0x99, 0x63, 0x58, 0x4c, 0xe5, 0x01, 0x3a, 0xe2, 0x96,
	0x03, 0x3d, 0x0b, 0xc9, 0x92, 0x75, 0xe8, 0x77, 0xf0, 0xb4, 0x09, 0xee, 0xab, 0x6c, 0x3b, 0xd0,
	0x37, 0xfc, 0x8a, 0x43, 0xbc, 0x97, 0xbc, 0xf5, 0x62, 0xac, 0x43, 0x57, 0xf0, 0xbe, 0xdd, 0xa5,
	0x4a, 0xff, 0x52, 0xa4, 0x46, 0x14, 0x7d, 0xcd, 0xcf, 0x9e, 0xcb, 0x9b, 0xf2, 0xcb, 0xd3, 0xb3,
	0xce, 0xd6, 0x31, 0x7f, 0x70, 0x79, 0x17, 0x00, 0x00, 0xff, 0xff, 0xed, 0x06, 0xe4, 0xdc, 0x9e,
	0x03, 0x00, 0x00,
}
