// Code generated by protoc-gen-go. DO NOT EDIT.
// source: answerManage/participantManage.proto

package answerManage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JudgeReq struct {
	ParticipantId        int64    `protobuf:"varint,1,opt,name=participantId,proto3" json:"participantId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JudgeReq) Reset()         { *m = JudgeReq{} }
func (m *JudgeReq) String() string { return proto.CompactTextString(m) }
func (*JudgeReq) ProtoMessage()    {}
func (*JudgeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb62960778388a61, []int{0}
}

func (m *JudgeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgeReq.Unmarshal(m, b)
}
func (m *JudgeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgeReq.Marshal(b, m, deterministic)
}
func (m *JudgeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgeReq.Merge(m, src)
}
func (m *JudgeReq) XXX_Size() int {
	return xxx_messageInfo_JudgeReq.Size(m)
}
func (m *JudgeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgeReq.DiscardUnknown(m)
}

var xxx_messageInfo_JudgeReq proto.InternalMessageInfo

func (m *JudgeReq) GetParticipantId() int64 {
	if m != nil {
		return m.ParticipantId
	}
	return 0
}

type JudgeRsp struct {
	AnswerFlag           bool     `protobuf:"varint,1,opt,name=answerFlag,proto3" json:"answerFlag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JudgeRsp) Reset()         { *m = JudgeRsp{} }
func (m *JudgeRsp) String() string { return proto.CompactTextString(m) }
func (*JudgeRsp) ProtoMessage()    {}
func (*JudgeRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb62960778388a61, []int{1}
}

func (m *JudgeRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgeRsp.Unmarshal(m, b)
}
func (m *JudgeRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgeRsp.Marshal(b, m, deterministic)
}
func (m *JudgeRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgeRsp.Merge(m, src)
}
func (m *JudgeRsp) XXX_Size() int {
	return xxx_messageInfo_JudgeRsp.Size(m)
}
func (m *JudgeRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgeRsp.DiscardUnknown(m)
}

var xxx_messageInfo_JudgeRsp proto.InternalMessageInfo

func (m *JudgeRsp) GetAnswerFlag() bool {
	if m != nil {
		return m.AnswerFlag
	}
	return false
}

type AddProblemHavedAnswerReq struct {
	ParticipantId        int64    `protobuf:"varint,1,opt,name=participantId,proto3" json:"participantId,omitempty"`
	ProblemId            int64    `protobuf:"varint,2,opt,name=problemId,proto3" json:"problemId,omitempty"`
	TeamId               int64    `protobuf:"varint,3,opt,name=teamId,proto3" json:"teamId,omitempty"`
	AnswerDate           string   `protobuf:"bytes,4,opt,name=answerDate,proto3" json:"answerDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProblemHavedAnswerReq) Reset()         { *m = AddProblemHavedAnswerReq{} }
func (m *AddProblemHavedAnswerReq) String() string { return proto.CompactTextString(m) }
func (*AddProblemHavedAnswerReq) ProtoMessage()    {}
func (*AddProblemHavedAnswerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb62960778388a61, []int{2}
}

func (m *AddProblemHavedAnswerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProblemHavedAnswerReq.Unmarshal(m, b)
}
func (m *AddProblemHavedAnswerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProblemHavedAnswerReq.Marshal(b, m, deterministic)
}
func (m *AddProblemHavedAnswerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProblemHavedAnswerReq.Merge(m, src)
}
func (m *AddProblemHavedAnswerReq) XXX_Size() int {
	return xxx_messageInfo_AddProblemHavedAnswerReq.Size(m)
}
func (m *AddProblemHavedAnswerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProblemHavedAnswerReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddProblemHavedAnswerReq proto.InternalMessageInfo

func (m *AddProblemHavedAnswerReq) GetParticipantId() int64 {
	if m != nil {
		return m.ParticipantId
	}
	return 0
}

func (m *AddProblemHavedAnswerReq) GetProblemId() int64 {
	if m != nil {
		return m.ProblemId
	}
	return 0
}

func (m *AddProblemHavedAnswerReq) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *AddProblemHavedAnswerReq) GetAnswerDate() string {
	if m != nil {
		return m.AnswerDate
	}
	return ""
}

type AddProblemHavedAnswerRsp struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProblemHavedAnswerRsp) Reset()         { *m = AddProblemHavedAnswerRsp{} }
func (m *AddProblemHavedAnswerRsp) String() string { return proto.CompactTextString(m) }
func (*AddProblemHavedAnswerRsp) ProtoMessage()    {}
func (*AddProblemHavedAnswerRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb62960778388a61, []int{3}
}

func (m *AddProblemHavedAnswerRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProblemHavedAnswerRsp.Unmarshal(m, b)
}
func (m *AddProblemHavedAnswerRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProblemHavedAnswerRsp.Marshal(b, m, deterministic)
}
func (m *AddProblemHavedAnswerRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProblemHavedAnswerRsp.Merge(m, src)
}
func (m *AddProblemHavedAnswerRsp) XXX_Size() int {
	return xxx_messageInfo_AddProblemHavedAnswerRsp.Size(m)
}
func (m *AddProblemHavedAnswerRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProblemHavedAnswerRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AddProblemHavedAnswerRsp proto.InternalMessageInfo

func (m *AddProblemHavedAnswerRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateWaitedAnswerReq struct {
	ParticipantId        int64    `protobuf:"varint,1,opt,name=participantId,proto3" json:"participantId,omitempty"`
	WaitedAnswer         string   `protobuf:"bytes,2,opt,name=waitedAnswer,proto3" json:"waitedAnswer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateWaitedAnswerReq) Reset()         { *m = UpdateWaitedAnswerReq{} }
func (m *UpdateWaitedAnswerReq) String() string { return proto.CompactTextString(m) }
func (*UpdateWaitedAnswerReq) ProtoMessage()    {}
func (*UpdateWaitedAnswerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb62960778388a61, []int{4}
}

func (m *UpdateWaitedAnswerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateWaitedAnswerReq.Unmarshal(m, b)
}
func (m *UpdateWaitedAnswerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateWaitedAnswerReq.Marshal(b, m, deterministic)
}
func (m *UpdateWaitedAnswerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateWaitedAnswerReq.Merge(m, src)
}
func (m *UpdateWaitedAnswerReq) XXX_Size() int {
	return xxx_messageInfo_UpdateWaitedAnswerReq.Size(m)
}
func (m *UpdateWaitedAnswerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateWaitedAnswerReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateWaitedAnswerReq proto.InternalMessageInfo

func (m *UpdateWaitedAnswerReq) GetParticipantId() int64 {
	if m != nil {
		return m.ParticipantId
	}
	return 0
}

func (m *UpdateWaitedAnswerReq) GetWaitedAnswer() string {
	if m != nil {
		return m.WaitedAnswer
	}
	return ""
}

type UpdateWaitedAnswerResp struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateWaitedAnswerResp) Reset()         { *m = UpdateWaitedAnswerResp{} }
func (m *UpdateWaitedAnswerResp) String() string { return proto.CompactTextString(m) }
func (*UpdateWaitedAnswerResp) ProtoMessage()    {}
func (*UpdateWaitedAnswerResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb62960778388a61, []int{5}
}

func (m *UpdateWaitedAnswerResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateWaitedAnswerResp.Unmarshal(m, b)
}
func (m *UpdateWaitedAnswerResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateWaitedAnswerResp.Marshal(b, m, deterministic)
}
func (m *UpdateWaitedAnswerResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateWaitedAnswerResp.Merge(m, src)
}
func (m *UpdateWaitedAnswerResp) XXX_Size() int {
	return xxx_messageInfo_UpdateWaitedAnswerResp.Size(m)
}
func (m *UpdateWaitedAnswerResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateWaitedAnswerResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateWaitedAnswerResp proto.InternalMessageInfo

func (m *UpdateWaitedAnswerResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateUserAnswerReq struct {
	ParticipantId        int64    `protobuf:"varint,1,opt,name=participantId,proto3" json:"participantId,omitempty"`
	ProblemId            int64    `protobuf:"varint,2,opt,name=problemId,proto3" json:"problemId,omitempty"`
	UserAnswer           string   `protobuf:"bytes,3,opt,name=userAnswer,proto3" json:"userAnswer,omitempty"`
	TrueOrFalse          bool     `protobuf:"varint,4,opt,name=trueOrFalse,proto3" json:"trueOrFalse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserAnswerReq) Reset()         { *m = UpdateUserAnswerReq{} }
func (m *UpdateUserAnswerReq) String() string { return proto.CompactTextString(m) }
func (*UpdateUserAnswerReq) ProtoMessage()    {}
func (*UpdateUserAnswerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb62960778388a61, []int{6}
}

func (m *UpdateUserAnswerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserAnswerReq.Unmarshal(m, b)
}
func (m *UpdateUserAnswerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserAnswerReq.Marshal(b, m, deterministic)
}
func (m *UpdateUserAnswerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserAnswerReq.Merge(m, src)
}
func (m *UpdateUserAnswerReq) XXX_Size() int {
	return xxx_messageInfo_UpdateUserAnswerReq.Size(m)
}
func (m *UpdateUserAnswerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserAnswerReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserAnswerReq proto.InternalMessageInfo

func (m *UpdateUserAnswerReq) GetParticipantId() int64 {
	if m != nil {
		return m.ParticipantId
	}
	return 0
}

func (m *UpdateUserAnswerReq) GetProblemId() int64 {
	if m != nil {
		return m.ProblemId
	}
	return 0
}

func (m *UpdateUserAnswerReq) GetUserAnswer() string {
	if m != nil {
		return m.UserAnswer
	}
	return ""
}

func (m *UpdateUserAnswerReq) GetTrueOrFalse() bool {
	if m != nil {
		return m.TrueOrFalse
	}
	return false
}

type UpdateUserAnswerRsp struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserAnswerRsp) Reset()         { *m = UpdateUserAnswerRsp{} }
func (m *UpdateUserAnswerRsp) String() string { return proto.CompactTextString(m) }
func (*UpdateUserAnswerRsp) ProtoMessage()    {}
func (*UpdateUserAnswerRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb62960778388a61, []int{7}
}

func (m *UpdateUserAnswerRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserAnswerRsp.Unmarshal(m, b)
}
func (m *UpdateUserAnswerRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserAnswerRsp.Marshal(b, m, deterministic)
}
func (m *UpdateUserAnswerRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserAnswerRsp.Merge(m, src)
}
func (m *UpdateUserAnswerRsp) XXX_Size() int {
	return xxx_messageInfo_UpdateUserAnswerRsp.Size(m)
}
func (m *UpdateUserAnswerRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserAnswerRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserAnswerRsp proto.InternalMessageInfo

func (m *UpdateUserAnswerRsp) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type PTeamEventIdReq struct {
	TeamId               int64    `protobuf:"varint,1,opt,name=teamId,proto3" json:"teamId,omitempty"`
	EventId              int64    `protobuf:"varint,2,opt,name=eventId,proto3" json:"eventId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PTeamEventIdReq) Reset()         { *m = PTeamEventIdReq{} }
func (m *PTeamEventIdReq) String() string { return proto.CompactTextString(m) }
func (*PTeamEventIdReq) ProtoMessage()    {}
func (*PTeamEventIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb62960778388a61, []int{8}
}

func (m *PTeamEventIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PTeamEventIdReq.Unmarshal(m, b)
}
func (m *PTeamEventIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PTeamEventIdReq.Marshal(b, m, deterministic)
}
func (m *PTeamEventIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PTeamEventIdReq.Merge(m, src)
}
func (m *PTeamEventIdReq) XXX_Size() int {
	return xxx_messageInfo_PTeamEventIdReq.Size(m)
}
func (m *PTeamEventIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PTeamEventIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_PTeamEventIdReq proto.InternalMessageInfo

func (m *PTeamEventIdReq) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *PTeamEventIdReq) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

type WaitAnswerRsp struct {
	ParticipantTime      string         `protobuf:"bytes,1,opt,name=participantTime,proto3" json:"participantTime,omitempty"`
	FillAnswerList       []*NolAnswer   `protobuf:"bytes,2,rep,name=fillAnswerList,proto3" json:"fillAnswerList,omitempty"`
	JudgeAnswerList      []*NolAnswer   `protobuf:"bytes,3,rep,name=judgeAnswerList,proto3" json:"judgeAnswerList,omitempty"`
	SingleAnswerList     []*NolAnswer   `protobuf:"bytes,4,rep,name=singleAnswerList,proto3" json:"singleAnswerList,omitempty"`
	MultiAnswerList      []*MultiAnswer `protobuf:"bytes,5,rep,name=multiAnswerList,proto3" json:"multiAnswerList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *WaitAnswerRsp) Reset()         { *m = WaitAnswerRsp{} }
func (m *WaitAnswerRsp) String() string { return proto.CompactTextString(m) }
func (*WaitAnswerRsp) ProtoMessage()    {}
func (*WaitAnswerRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb62960778388a61, []int{9}
}

func (m *WaitAnswerRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaitAnswerRsp.Unmarshal(m, b)
}
func (m *WaitAnswerRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaitAnswerRsp.Marshal(b, m, deterministic)
}
func (m *WaitAnswerRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaitAnswerRsp.Merge(m, src)
}
func (m *WaitAnswerRsp) XXX_Size() int {
	return xxx_messageInfo_WaitAnswerRsp.Size(m)
}
func (m *WaitAnswerRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_WaitAnswerRsp.DiscardUnknown(m)
}

var xxx_messageInfo_WaitAnswerRsp proto.InternalMessageInfo

func (m *WaitAnswerRsp) GetParticipantTime() string {
	if m != nil {
		return m.ParticipantTime
	}
	return ""
}

func (m *WaitAnswerRsp) GetFillAnswerList() []*NolAnswer {
	if m != nil {
		return m.FillAnswerList
	}
	return nil
}

func (m *WaitAnswerRsp) GetJudgeAnswerList() []*NolAnswer {
	if m != nil {
		return m.JudgeAnswerList
	}
	return nil
}

func (m *WaitAnswerRsp) GetSingleAnswerList() []*NolAnswer {
	if m != nil {
		return m.SingleAnswerList
	}
	return nil
}

func (m *WaitAnswerRsp) GetMultiAnswerList() []*MultiAnswer {
	if m != nil {
		return m.MultiAnswerList
	}
	return nil
}

type NolAnswer struct {
	ProblemId            string   `protobuf:"bytes,1,opt,name=problemId,proto3" json:"problemId,omitempty"`
	Answer               string   `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NolAnswer) Reset()         { *m = NolAnswer{} }
func (m *NolAnswer) String() string { return proto.CompactTextString(m) }
func (*NolAnswer) ProtoMessage()    {}
func (*NolAnswer) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb62960778388a61, []int{10}
}

func (m *NolAnswer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NolAnswer.Unmarshal(m, b)
}
func (m *NolAnswer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NolAnswer.Marshal(b, m, deterministic)
}
func (m *NolAnswer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NolAnswer.Merge(m, src)
}
func (m *NolAnswer) XXX_Size() int {
	return xxx_messageInfo_NolAnswer.Size(m)
}
func (m *NolAnswer) XXX_DiscardUnknown() {
	xxx_messageInfo_NolAnswer.DiscardUnknown(m)
}

var xxx_messageInfo_NolAnswer proto.InternalMessageInfo

func (m *NolAnswer) GetProblemId() string {
	if m != nil {
		return m.ProblemId
	}
	return ""
}

func (m *NolAnswer) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

type MultiAnswer struct {
	ProblemId            string    `protobuf:"bytes,1,opt,name=problemId,proto3" json:"problemId,omitempty"`
	Answer               []float64 `protobuf:"fixed64,2,rep,packed,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MultiAnswer) Reset()         { *m = MultiAnswer{} }
func (m *MultiAnswer) String() string { return proto.CompactTextString(m) }
func (*MultiAnswer) ProtoMessage()    {}
func (*MultiAnswer) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb62960778388a61, []int{11}
}

func (m *MultiAnswer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiAnswer.Unmarshal(m, b)
}
func (m *MultiAnswer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiAnswer.Marshal(b, m, deterministic)
}
func (m *MultiAnswer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiAnswer.Merge(m, src)
}
func (m *MultiAnswer) XXX_Size() int {
	return xxx_messageInfo_MultiAnswer.Size(m)
}
func (m *MultiAnswer) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiAnswer.DiscardUnknown(m)
}

var xxx_messageInfo_MultiAnswer proto.InternalMessageInfo

func (m *MultiAnswer) GetProblemId() string {
	if m != nil {
		return m.ProblemId
	}
	return ""
}

func (m *MultiAnswer) GetAnswer() []float64 {
	if m != nil {
		return m.Answer
	}
	return nil
}

type ParticipantIdReq struct {
	ParticipantId        int64    `protobuf:"varint,1,opt,name=participantId,proto3" json:"participantId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParticipantIdReq) Reset()         { *m = ParticipantIdReq{} }
func (m *ParticipantIdReq) String() string { return proto.CompactTextString(m) }
func (*ParticipantIdReq) ProtoMessage()    {}
func (*ParticipantIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb62960778388a61, []int{12}
}

func (m *ParticipantIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParticipantIdReq.Unmarshal(m, b)
}
func (m *ParticipantIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParticipantIdReq.Marshal(b, m, deterministic)
}
func (m *ParticipantIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParticipantIdReq.Merge(m, src)
}
func (m *ParticipantIdReq) XXX_Size() int {
	return xxx_messageInfo_ParticipantIdReq.Size(m)
}
func (m *ParticipantIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ParticipantIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_ParticipantIdReq proto.InternalMessageInfo

func (m *ParticipantIdReq) GetParticipantId() int64 {
	if m != nil {
		return m.ParticipantId
	}
	return 0
}

type AnswerTimeReq struct {
	AnswerTime           string   `protobuf:"bytes,1,opt,name=answerTime,proto3" json:"answerTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnswerTimeReq) Reset()         { *m = AnswerTimeReq{} }
func (m *AnswerTimeReq) String() string { return proto.CompactTextString(m) }
func (*AnswerTimeReq) ProtoMessage()    {}
func (*AnswerTimeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb62960778388a61, []int{13}
}

func (m *AnswerTimeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnswerTimeReq.Unmarshal(m, b)
}
func (m *AnswerTimeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnswerTimeReq.Marshal(b, m, deterministic)
}
func (m *AnswerTimeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnswerTimeReq.Merge(m, src)
}
func (m *AnswerTimeReq) XXX_Size() int {
	return xxx_messageInfo_AnswerTimeReq.Size(m)
}
func (m *AnswerTimeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AnswerTimeReq.DiscardUnknown(m)
}

var xxx_messageInfo_AnswerTimeReq proto.InternalMessageInfo

func (m *AnswerTimeReq) GetAnswerTime() string {
	if m != nil {
		return m.AnswerTime
	}
	return ""
}

type ParticipantMember struct {
	LeaderId             int64    `protobuf:"varint,1,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	MemberId             []int64  `protobuf:"varint,2,rep,packed,name=memberId,proto3" json:"memberId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParticipantMember) Reset()         { *m = ParticipantMember{} }
func (m *ParticipantMember) String() string { return proto.CompactTextString(m) }
func (*ParticipantMember) ProtoMessage()    {}
func (*ParticipantMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb62960778388a61, []int{14}
}

func (m *ParticipantMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParticipantMember.Unmarshal(m, b)
}
func (m *ParticipantMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParticipantMember.Marshal(b, m, deterministic)
}
func (m *ParticipantMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParticipantMember.Merge(m, src)
}
func (m *ParticipantMember) XXX_Size() int {
	return xxx_messageInfo_ParticipantMember.Size(m)
}
func (m *ParticipantMember) XXX_DiscardUnknown() {
	xxx_messageInfo_ParticipantMember.DiscardUnknown(m)
}

var xxx_messageInfo_ParticipantMember proto.InternalMessageInfo

func (m *ParticipantMember) GetLeaderId() int64 {
	if m != nil {
		return m.LeaderId
	}
	return 0
}

func (m *ParticipantMember) GetMemberId() []int64 {
	if m != nil {
		return m.MemberId
	}
	return nil
}

type EPInsertReq struct {
	EventId               int64                `protobuf:"varint,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	ParticipantMemberList []*ParticipantMember `protobuf:"bytes,2,rep,name=participantMemberList,proto3" json:"participantMemberList,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}             `json:"-"`
	XXX_unrecognized      []byte               `json:"-"`
	XXX_sizecache         int32                `json:"-"`
}

func (m *EPInsertReq) Reset()         { *m = EPInsertReq{} }
func (m *EPInsertReq) String() string { return proto.CompactTextString(m) }
func (*EPInsertReq) ProtoMessage()    {}
func (*EPInsertReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb62960778388a61, []int{15}
}

func (m *EPInsertReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EPInsertReq.Unmarshal(m, b)
}
func (m *EPInsertReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EPInsertReq.Marshal(b, m, deterministic)
}
func (m *EPInsertReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EPInsertReq.Merge(m, src)
}
func (m *EPInsertReq) XXX_Size() int {
	return xxx_messageInfo_EPInsertReq.Size(m)
}
func (m *EPInsertReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EPInsertReq.DiscardUnknown(m)
}

var xxx_messageInfo_EPInsertReq proto.InternalMessageInfo

func (m *EPInsertReq) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *EPInsertReq) GetParticipantMemberList() []*ParticipantMember {
	if m != nil {
		return m.ParticipantMemberList
	}
	return nil
}

type EPInsertRsp struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EPInsertRsp) Reset()         { *m = EPInsertRsp{} }
func (m *EPInsertRsp) String() string { return proto.CompactTextString(m) }
func (*EPInsertRsp) ProtoMessage()    {}
func (*EPInsertRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb62960778388a61, []int{16}
}

func (m *EPInsertRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EPInsertRsp.Unmarshal(m, b)
}
func (m *EPInsertRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EPInsertRsp.Marshal(b, m, deterministic)
}
func (m *EPInsertRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EPInsertRsp.Merge(m, src)
}
func (m *EPInsertRsp) XXX_Size() int {
	return xxx_messageInfo_EPInsertRsp.Size(m)
}
func (m *EPInsertRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_EPInsertRsp.DiscardUnknown(m)
}

var xxx_messageInfo_EPInsertRsp proto.InternalMessageInfo

func (m *EPInsertRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetPListByUserIdReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPListByUserIdReq) Reset()         { *m = GetPListByUserIdReq{} }
func (m *GetPListByUserIdReq) String() string { return proto.CompactTextString(m) }
func (*GetPListByUserIdReq) ProtoMessage()    {}
func (*GetPListByUserIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb62960778388a61, []int{17}
}

func (m *GetPListByUserIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPListByUserIdReq.Unmarshal(m, b)
}
func (m *GetPListByUserIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPListByUserIdReq.Marshal(b, m, deterministic)
}
func (m *GetPListByUserIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPListByUserIdReq.Merge(m, src)
}
func (m *GetPListByUserIdReq) XXX_Size() int {
	return xxx_messageInfo_GetPListByUserIdReq.Size(m)
}
func (m *GetPListByUserIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPListByUserIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetPListByUserIdReq proto.InternalMessageInfo

func (m *GetPListByUserIdReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type PEMessage struct {
	ParticipantId        int64    `protobuf:"varint,1,opt,name=participantId,proto3" json:"participantId,omitempty"`
	ReferEventId         int64    `protobuf:"varint,2,opt,name=referEventId,proto3" json:"referEventId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PEMessage) Reset()         { *m = PEMessage{} }
func (m *PEMessage) String() string { return proto.CompactTextString(m) }
func (*PEMessage) ProtoMessage()    {}
func (*PEMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb62960778388a61, []int{18}
}

func (m *PEMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PEMessage.Unmarshal(m, b)
}
func (m *PEMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PEMessage.Marshal(b, m, deterministic)
}
func (m *PEMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PEMessage.Merge(m, src)
}
func (m *PEMessage) XXX_Size() int {
	return xxx_messageInfo_PEMessage.Size(m)
}
func (m *PEMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PEMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PEMessage proto.InternalMessageInfo

func (m *PEMessage) GetParticipantId() int64 {
	if m != nil {
		return m.ParticipantId
	}
	return 0
}

func (m *PEMessage) GetReferEventId() int64 {
	if m != nil {
		return m.ReferEventId
	}
	return 0
}

type PEMessageList struct {
	PEList               []*PEMessage `protobuf:"bytes,1,rep,name=PEList,proto3" json:"PEList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PEMessageList) Reset()         { *m = PEMessageList{} }
func (m *PEMessageList) String() string { return proto.CompactTextString(m) }
func (*PEMessageList) ProtoMessage()    {}
func (*PEMessageList) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb62960778388a61, []int{19}
}

func (m *PEMessageList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PEMessageList.Unmarshal(m, b)
}
func (m *PEMessageList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PEMessageList.Marshal(b, m, deterministic)
}
func (m *PEMessageList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PEMessageList.Merge(m, src)
}
func (m *PEMessageList) XXX_Size() int {
	return xxx_messageInfo_PEMessageList.Size(m)
}
func (m *PEMessageList) XXX_DiscardUnknown() {
	xxx_messageInfo_PEMessageList.DiscardUnknown(m)
}

var xxx_messageInfo_PEMessageList proto.InternalMessageInfo

func (m *PEMessageList) GetPEList() []*PEMessage {
	if m != nil {
		return m.PEList
	}
	return nil
}

type PUserEventIdReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	EventId              int64    `protobuf:"varint,2,opt,name=eventId,proto3" json:"eventId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PUserEventIdReq) Reset()         { *m = PUserEventIdReq{} }
func (m *PUserEventIdReq) String() string { return proto.CompactTextString(m) }
func (*PUserEventIdReq) ProtoMessage()    {}
func (*PUserEventIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb62960778388a61, []int{20}
}

func (m *PUserEventIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PUserEventIdReq.Unmarshal(m, b)
}
func (m *PUserEventIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PUserEventIdReq.Marshal(b, m, deterministic)
}
func (m *PUserEventIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PUserEventIdReq.Merge(m, src)
}
func (m *PUserEventIdReq) XXX_Size() int {
	return xxx_messageInfo_PUserEventIdReq.Size(m)
}
func (m *PUserEventIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PUserEventIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_PUserEventIdReq proto.InternalMessageInfo

func (m *PUserEventIdReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PUserEventIdReq) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

type ParticipantMessage struct {
	ParticipantId        int64    `protobuf:"varint,1,opt,name=participantId,proto3" json:"participantId,omitempty"`
	EventId              int64    `protobuf:"varint,2,opt,name=eventId,proto3" json:"eventId,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	TeamId               int64    `protobuf:"varint,4,opt,name=teamId,proto3" json:"teamId,omitempty"`
	Credit               float64  `protobuf:"fixed64,5,opt,name=credit,proto3" json:"credit,omitempty"`
	Leader               bool     `protobuf:"varint,6,opt,name=leader,proto3" json:"leader,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParticipantMessage) Reset()         { *m = ParticipantMessage{} }
func (m *ParticipantMessage) String() string { return proto.CompactTextString(m) }
func (*ParticipantMessage) ProtoMessage()    {}
func (*ParticipantMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb62960778388a61, []int{21}
}

func (m *ParticipantMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParticipantMessage.Unmarshal(m, b)
}
func (m *ParticipantMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParticipantMessage.Marshal(b, m, deterministic)
}
func (m *ParticipantMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParticipantMessage.Merge(m, src)
}
func (m *ParticipantMessage) XXX_Size() int {
	return xxx_messageInfo_ParticipantMessage.Size(m)
}
func (m *ParticipantMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ParticipantMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ParticipantMessage proto.InternalMessageInfo

func (m *ParticipantMessage) GetParticipantId() int64 {
	if m != nil {
		return m.ParticipantId
	}
	return 0
}

func (m *ParticipantMessage) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *ParticipantMessage) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ParticipantMessage) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *ParticipantMessage) GetCredit() float64 {
	if m != nil {
		return m.Credit
	}
	return 0
}

func (m *ParticipantMessage) GetLeader() bool {
	if m != nil {
		return m.Leader
	}
	return false
}

type ParticipantMessageList struct {
	PEList               []*ParticipantMessage `protobuf:"bytes,1,rep,name=PEList,proto3" json:"PEList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ParticipantMessageList) Reset()         { *m = ParticipantMessageList{} }
func (m *ParticipantMessageList) String() string { return proto.CompactTextString(m) }
func (*ParticipantMessageList) ProtoMessage()    {}
func (*ParticipantMessageList) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb62960778388a61, []int{22}
}

func (m *ParticipantMessageList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParticipantMessageList.Unmarshal(m, b)
}
func (m *ParticipantMessageList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParticipantMessageList.Marshal(b, m, deterministic)
}
func (m *ParticipantMessageList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParticipantMessageList.Merge(m, src)
}
func (m *ParticipantMessageList) XXX_Size() int {
	return xxx_messageInfo_ParticipantMessageList.Size(m)
}
func (m *ParticipantMessageList) XXX_DiscardUnknown() {
	xxx_messageInfo_ParticipantMessageList.DiscardUnknown(m)
}

var xxx_messageInfo_ParticipantMessageList proto.InternalMessageInfo

func (m *ParticipantMessageList) GetPEList() []*ParticipantMessage {
	if m != nil {
		return m.PEList
	}
	return nil
}

func init() {
	proto.RegisterType((*JudgeReq)(nil), "JudgeReq")
	proto.RegisterType((*JudgeRsp)(nil), "JudgeRsp")
	proto.RegisterType((*AddProblemHavedAnswerReq)(nil), "AddProblemHavedAnswerReq")
	proto.RegisterType((*AddProblemHavedAnswerRsp)(nil), "AddProblemHavedAnswerRsp")
	proto.RegisterType((*UpdateWaitedAnswerReq)(nil), "UpdateWaitedAnswerReq")
	proto.RegisterType((*UpdateWaitedAnswerResp)(nil), "UpdateWaitedAnswerResp")
	proto.RegisterType((*UpdateUserAnswerReq)(nil), "UpdateUserAnswerReq")
	proto.RegisterType((*UpdateUserAnswerRsp)(nil), "UpdateUserAnswerRsp")
	proto.RegisterType((*PTeamEventIdReq)(nil), "PTeamEventIdReq")
	proto.RegisterType((*WaitAnswerRsp)(nil), "WaitAnswerRsp")
	proto.RegisterType((*NolAnswer)(nil), "nolAnswer")
	proto.RegisterType((*MultiAnswer)(nil), "multiAnswer")
	proto.RegisterType((*ParticipantIdReq)(nil), "ParticipantIdReq")
	proto.RegisterType((*AnswerTimeReq)(nil), "AnswerTimeReq")
	proto.RegisterType((*ParticipantMember)(nil), "ParticipantMember")
	proto.RegisterType((*EPInsertReq)(nil), "EPInsertReq")
	proto.RegisterType((*EPInsertRsp)(nil), "EPInsertRsp")
	proto.RegisterType((*GetPListByUserIdReq)(nil), "GetPListByUserIdReq")
	proto.RegisterType((*PEMessage)(nil), "PEMessage")
	proto.RegisterType((*PEMessageList)(nil), "PEMessageList")
	proto.RegisterType((*PUserEventIdReq)(nil), "PUserEventIdReq")
	proto.RegisterType((*ParticipantMessage)(nil), "ParticipantMessage")
	proto.RegisterType((*ParticipantMessageList)(nil), "ParticipantMessageList")
}

func init() {
	proto.RegisterFile("answerManage/participantManage.proto", fileDescriptor_fb62960778388a61)
}

var fileDescriptor_fb62960778388a61 = []byte{
	// 888 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xef, 0x4e, 0xe3, 0x46,
	0x10, 0x8f, 0x09, 0x97, 0x8b, 0x27, 0x84, 0x84, 0xe5, 0x08, 0xae, 0x75, 0xbd, 0x46, 0xab, 0x93,
	0x1a, 0xf5, 0x74, 0x4b, 0x15, 0x10, 0xea, 0xc7, 0x86, 0x10, 0x42, 0xda, 0x22, 0x22, 0x0b, 0xd4,
	0xcf, 0x0b, 0x5e, 0x22, 0x57, 0x4e, 0x62, 0xd6, 0x0e, 0x88, 0xe7, 0xa8, 0xd4, 0x2f, 0x7d, 0x8d,
	0xbe, 0x41, 0x5f, 0xac, 0xda, 0xf5, 0x9f, 0xec, 0x3a, 0x0e, 0x0a, 0x52, 0xbf, 0x79, 0x66, 0xe7,
	0xff, 0xfc, 0x66, 0x3c, 0xf0, 0x99, 0xce, 0xc2, 0x67, 0xc6, 0xaf, 0xe8, 0x8c, 0x4e, 0xd8, 0x51,
	0x40, 0x79, 0xe4, 0xdd, 0x7b, 0x01, 0x9d, 0x45, 0x31, 0x87, 0x04, 0x7c, 0x1e, 0xcd, 0xf1, 0x8f,
	0x50, 0xfd, 0x65, 0xe1, 0x4e, 0x98, 0xc3, 0x1e, 0xd1, 0x67, 0xa8, 0x2b, 0x62, 0x23, 0xd7, 0x32,
	0xda, 0x46, 0xa7, 0xec, 0xe8, 0x4c, 0xfc, 0x43, 0xaa, 0x11, 0x06, 0xe8, 0x13, 0x40, 0xec, 0xe5,
	0xc2, 0xa7, 0x13, 0x29, 0x5e, 0x75, 0x14, 0x0e, 0xfe, 0xcb, 0x00, 0xab, 0xe7, 0xba, 0x63, 0x3e,
	0xbf, 0xf3, 0xd9, 0xf4, 0x92, 0x3e, 0x31, 0xb7, 0x27, 0x5f, 0x37, 0x76, 0x87, 0x3e, 0x82, 0x19,
	0xc4, 0xea, 0x23, 0xd7, 0xda, 0x92, 0x12, 0x4b, 0x06, 0x6a, 0x41, 0x25, 0x62, 0x54, 0x3c, 0x95,
	0xe5, 0x53, 0x42, 0x2d, 0x03, 0x3b, 0xa7, 0x11, 0xb3, 0xb6, 0xdb, 0x46, 0xc7, 0x74, 0x14, 0x0e,
	0x3e, 0x59, 0x17, 0x57, 0x18, 0x20, 0x0b, 0xde, 0x4f, 0x59, 0x18, 0xd2, 0x09, 0x93, 0x11, 0x99,
	0x4e, 0x4a, 0x62, 0x0a, 0x07, 0xb7, 0x81, 0x4b, 0x23, 0xf6, 0x3b, 0xf5, 0xa2, 0xb7, 0xa7, 0x82,
	0x61, 0xe7, 0x59, 0x51, 0x94, 0xd9, 0x98, 0x8e, 0xc6, 0xc3, 0x5d, 0x68, 0x15, 0xb9, 0x78, 0x35,
	0xac, 0xbf, 0x0d, 0xd8, 0x8f, 0x95, 0x6e, 0x43, 0xc6, 0xff, 0xdf, 0x02, 0x7f, 0x02, 0x58, 0x64,
	0x46, 0x65, 0x91, 0x4d, 0x47, 0xe1, 0xa0, 0x36, 0xd4, 0x22, 0xbe, 0x60, 0xd7, 0xfc, 0x82, 0xfa,
	0x61, 0x5c, 0xe9, 0xaa, 0xa3, 0xb2, 0xf0, 0xd7, 0x82, 0xe0, 0xc2, 0x40, 0x74, 0x8e, 0xb3, 0x70,
	0xe1, 0x47, 0x49, 0x36, 0x09, 0x85, 0xfb, 0xd0, 0x18, 0xdf, 0x30, 0x3a, 0x1d, 0x3c, 0x31, 0x11,
	0x9e, 0xc8, 0x63, 0xd9, 0x64, 0x43, 0x6b, 0xb2, 0x05, 0xef, 0x59, 0x2c, 0x95, 0xc4, 0x9d, 0x92,
	0xf8, 0xcf, 0x2d, 0xa8, 0x8b, 0x02, 0x2e, 0xdd, 0x75, 0xa0, 0xa1, 0xa4, 0x7d, 0xe3, 0x4d, 0xd3,
	0x2a, 0xe6, 0xd9, 0xa8, 0x0b, 0xbb, 0x0f, 0x9e, 0xef, 0xc7, 0xaa, 0xbf, 0x79, 0x61, 0x64, 0x6d,
	0xb5, 0xcb, 0x9d, 0x5a, 0x17, 0xc8, 0x6c, 0x9e, 0x70, 0x9d, 0x9c, 0x04, 0x3a, 0x81, 0xc6, 0x1f,
	0x62, 0x26, 0x14, 0xa5, 0xf2, 0x8a, 0x52, 0x5e, 0x04, 0x9d, 0x42, 0x33, 0xf4, 0x66, 0x13, 0x5f,
	0x55, 0xdb, 0x5e, 0x51, 0x5b, 0x91, 0x41, 0xa7, 0xd0, 0x98, 0x2e, 0xfc, 0xc8, 0x53, 0xd4, 0xde,
	0x49, 0xb5, 0x1d, 0xa2, 0xf0, 0x9d, 0xbc, 0x10, 0xee, 0x81, 0x99, 0x99, 0xd5, 0xdb, 0x1e, 0x97,
	0x42, 0x9f, 0x2b, 0xaa, 0x82, 0x34, 0xa1, 0x70, 0x1f, 0x6a, 0x8a, 0xd5, 0x37, 0x18, 0x29, 0x77,
	0x8c, 0xcc, 0xc8, 0x4f, 0xd0, 0x1c, 0xab, 0x10, 0xdc, 0x7c, 0xf7, 0x1c, 0x41, 0x3d, 0xf6, 0x2c,
	0x3a, 0x25, 0xd4, 0xb2, 0x39, 0x57, 0x3a, 0xaa, 0x70, 0xf0, 0xaf, 0xb0, 0xa7, 0xb8, 0xba, 0x62,
	0xd3, 0x3b, 0xc6, 0x91, 0x0d, 0x55, 0x9f, 0x51, 0x97, 0xf1, 0xcc, 0x4d, 0x46, 0x8b, 0xb7, 0xa9,
	0x94, 0x92, 0xa0, 0x2a, 0x8b, 0xb7, 0x94, 0xc6, 0x8f, 0x50, 0x1b, 0x8c, 0x47, 0xb3, 0x90, 0xf1,
	0x48, 0xf8, 0x56, 0xe0, 0x67, 0x68, 0xf0, 0x43, 0x97, 0x70, 0x10, 0xe4, 0xbd, 0x2a, 0x48, 0x42,
	0x64, 0x25, 0x26, 0xa7, 0x58, 0x01, 0x7f, 0xaf, 0xb8, 0x7c, 0x75, 0x07, 0x7c, 0x85, 0xfd, 0x21,
	0x8b, 0xc6, 0x42, 0xe9, 0xec, 0x45, 0x4c, 0x5a, 0x36, 0x3a, 0x8b, 0x50, 0x49, 0x34, 0xa1, 0xf0,
	0x2d, 0x98, 0xe3, 0xc1, 0x55, 0xac, 0xbb, 0xf9, 0xf6, 0xe2, 0xec, 0x81, 0xf1, 0x81, 0x36, 0x72,
	0x1a, 0x0f, 0x1f, 0x43, 0x3d, 0x33, 0x2b, 0xa1, 0x8a, 0xa1, 0x32, 0x1e, 0xc8, 0xd4, 0x8d, 0x04,
	0xd8, 0xd9, 0xbb, 0x93, 0xbc, 0xc8, 0x89, 0x17, 0x11, 0xeb, 0x13, 0x5f, 0x14, 0xf6, 0x2b, 0x13,
	0xff, 0x8f, 0x01, 0x48, 0xab, 0xea, 0x5b, 0x52, 0x5b, 0x6b, 0x56, 0x09, 0xa4, 0xac, 0x05, 0xb2,
	0x5c, 0x49, 0xdb, 0xda, 0x4a, 0x6a, 0x41, 0xe5, 0x9e, 0x33, 0xd7, 0x13, 0x13, 0x69, 0x08, 0xc8,
	0xc7, 0x94, 0xe0, 0xc7, 0x10, 0xb3, 0x2a, 0x72, 0x43, 0x26, 0x14, 0x1e, 0x40, 0x6b, 0x35, 0x6a,
	0x59, 0xb9, 0x2f, 0xb9, 0xca, 0xed, 0x93, 0x55, 0xc1, 0xb4, 0x84, 0xdd, 0x7f, 0xdf, 0xe9, 0x38,
	0x97, 0x7f, 0x78, 0x74, 0x0a, 0x2d, 0x59, 0x53, 0x75, 0xd8, 0x24, 0x94, 0xd0, 0x0e, 0x51, 0x80,
	0x6c, 0x2b, 0x54, 0x18, 0xe0, 0x12, 0x3a, 0x07, 0x5b, 0x60, 0x69, 0xa9, 0xa5, 0xa2, 0x0a, 0x7d,
	0x20, 0x05, 0x40, 0xb3, 0x77, 0x89, 0xd6, 0x78, 0x5c, 0x42, 0x43, 0xf8, 0xa8, 0x5b, 0x89, 0xc5,
	0x7b, 0x33, 0x57, 0x06, 0x85, 0x9a, 0x24, 0xd7, 0x75, 0xbb, 0x28, 0x45, 0x5c, 0x42, 0x17, 0xf0,
	0xdd, 0x90, 0x45, 0xfd, 0x39, 0xe7, 0xec, 0x3e, 0xd9, 0xe8, 0x67, 0x2f, 0xda, 0x02, 0x41, 0x7b,
	0x24, 0xbf, 0x50, 0xec, 0x5d, 0xa2, 0xfd, 0x00, 0x70, 0x09, 0xf5, 0x65, 0x40, 0xcb, 0xfd, 0xb1,
	0x91, 0x11, 0x6d, 0xdd, 0xc8, 0x60, 0x0e, 0x87, 0x2c, 0x99, 0xd0, 0xbe, 0xec, 0xed, 0xd9, 0xcb,
	0x4d, 0xdc, 0xfb, 0x26, 0xc9, 0xfd, 0xb8, 0xec, 0x43, 0x52, 0xdc, 0x5c, 0x5c, 0x42, 0x3f, 0x43,
	0x33, 0xff, 0x57, 0x44, 0x1f, 0x48, 0xc1, 0x5f, 0xdc, 0x2e, 0xe0, 0xca, 0x74, 0x1c, 0xf8, 0x36,
	0x7e, 0x50, 0x7c, 0xa8, 0x47, 0x03, 0x6a, 0x91, 0xc2, 0x63, 0xc5, 0x3e, 0x24, 0xc5, 0x17, 0x06,
	0x2e, 0xa1, 0x2f, 0xb0, 0x27, 0x6f, 0xbb, 0xd1, 0x83, 0xb8, 0x89, 0x12, 0x3b, 0x26, 0x49, 0x2f,
	0x44, 0x3b, 0xfd, 0x94, 0xc2, 0xd7, 0x70, 0x50, 0x78, 0x43, 0xa1, 0x6f, 0xc8, 0xba, 0x9b, 0xcf,
	0x5e, 0xf7, 0x24, 0x0c, 0xde, 0x55, 0xe4, 0x49, 0x7a, 0xfc, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x56, 0xb6, 0xbc, 0x98, 0xba, 0x0a, 0x00, 0x00,
}
