// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: unionManage.proto

/*
Package unionManage is a generated protocol buffer package.

It is generated from these files:
	unionManage.proto

It has these top-level messages:
	GetProblemNoAnswerReq
	UnionProblemNum
	GetProblemNoAnswerRsp
	ProblemItem
*/
package unionManage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UnionManage service

type UnionManageService interface {
	// 生成用户每日答题题目
	GetProblemNoAnswer(ctx context.Context, in *GetProblemNoAnswerReq, opts ...client.CallOption) (*GetProblemNoAnswerRsp, error)
}

type unionManageService struct {
	c    client.Client
	name string
}

func NewUnionManageService(name string, c client.Client) UnionManageService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "unionmanage"
	}
	return &unionManageService{
		c:    c,
		name: name,
	}
}

func (c *unionManageService) GetProblemNoAnswer(ctx context.Context, in *GetProblemNoAnswerReq, opts ...client.CallOption) (*GetProblemNoAnswerRsp, error) {
	req := c.c.NewRequest(c.name, "UnionManage.GetProblemNoAnswer", in)
	out := new(GetProblemNoAnswerRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UnionManage service

type UnionManageHandler interface {
	// 生成用户每日答题题目
	GetProblemNoAnswer(context.Context, *GetProblemNoAnswerReq, *GetProblemNoAnswerRsp) error
}

func RegisterUnionManageHandler(s server.Server, hdlr UnionManageHandler, opts ...server.HandlerOption) error {
	type unionManage interface {
		GetProblemNoAnswer(ctx context.Context, in *GetProblemNoAnswerReq, out *GetProblemNoAnswerRsp) error
	}
	type UnionManage struct {
		unionManage
	}
	h := &unionManageHandler{hdlr}
	return s.Handle(s.NewHandler(&UnionManage{h}, opts...))
}

type unionManageHandler struct {
	UnionManageHandler
}

func (h *unionManageHandler) GetProblemNoAnswer(ctx context.Context, in *GetProblemNoAnswerReq, out *GetProblemNoAnswerRsp) error {
	return h.UnionManageHandler.GetProblemNoAnswer(ctx, in, out)
}
