// Code generated by protoc-gen-go. DO NOT EDIT.
// source: unionManage/unionManage.proto

package unionManage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetProblemNoAnswerReq struct {
	UserId               int64       `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	EventId              int64       `protobuf:"varint,2,opt,name=eventId,proto3" json:"eventId,omitempty"`
	TeamId               int64       `protobuf:"varint,3,opt,name=teamId,proto3" json:"teamId,omitempty"`
	PaticipantId         int64       `protobuf:"varint,4,opt,name=paticipantId,proto3" json:"paticipantId,omitempty"`
	ProblemNum           *ProblemNum `protobuf:"bytes,5,opt,name=problemNum,proto3" json:"problemNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetProblemNoAnswerReq) Reset()         { *m = GetProblemNoAnswerReq{} }
func (m *GetProblemNoAnswerReq) String() string { return proto.CompactTextString(m) }
func (*GetProblemNoAnswerReq) ProtoMessage()    {}
func (*GetProblemNoAnswerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7616ba6b28107807, []int{0}
}

func (m *GetProblemNoAnswerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProblemNoAnswerReq.Unmarshal(m, b)
}
func (m *GetProblemNoAnswerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProblemNoAnswerReq.Marshal(b, m, deterministic)
}
func (m *GetProblemNoAnswerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProblemNoAnswerReq.Merge(m, src)
}
func (m *GetProblemNoAnswerReq) XXX_Size() int {
	return xxx_messageInfo_GetProblemNoAnswerReq.Size(m)
}
func (m *GetProblemNoAnswerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProblemNoAnswerReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProblemNoAnswerReq proto.InternalMessageInfo

func (m *GetProblemNoAnswerReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetProblemNoAnswerReq) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *GetProblemNoAnswerReq) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *GetProblemNoAnswerReq) GetPaticipantId() int64 {
	if m != nil {
		return m.PaticipantId
	}
	return 0
}

func (m *GetProblemNoAnswerReq) GetProblemNum() *ProblemNum {
	if m != nil {
		return m.ProblemNum
	}
	return nil
}

type ProblemNum struct {
	Single               int32    `protobuf:"varint,1,opt,name=single,proto3" json:"single,omitempty"`
	Multiple             int32    `protobuf:"varint,2,opt,name=multiple,proto3" json:"multiple,omitempty"`
	Fill                 int32    `protobuf:"varint,3,opt,name=fill,proto3" json:"fill,omitempty"`
	Judge                int32    `protobuf:"varint,4,opt,name=judge,proto3" json:"judge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProblemNum) Reset()         { *m = ProblemNum{} }
func (m *ProblemNum) String() string { return proto.CompactTextString(m) }
func (*ProblemNum) ProtoMessage()    {}
func (*ProblemNum) Descriptor() ([]byte, []int) {
	return fileDescriptor_7616ba6b28107807, []int{1}
}

func (m *ProblemNum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemNum.Unmarshal(m, b)
}
func (m *ProblemNum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemNum.Marshal(b, m, deterministic)
}
func (m *ProblemNum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemNum.Merge(m, src)
}
func (m *ProblemNum) XXX_Size() int {
	return xxx_messageInfo_ProblemNum.Size(m)
}
func (m *ProblemNum) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemNum.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemNum proto.InternalMessageInfo

func (m *ProblemNum) GetSingle() int32 {
	if m != nil {
		return m.Single
	}
	return 0
}

func (m *ProblemNum) GetMultiple() int32 {
	if m != nil {
		return m.Multiple
	}
	return 0
}

func (m *ProblemNum) GetFill() int32 {
	if m != nil {
		return m.Fill
	}
	return 0
}

func (m *ProblemNum) GetJudge() int32 {
	if m != nil {
		return m.Judge
	}
	return 0
}

type GetProblemNoAnswerRsp struct {
	Single               []*ProblemItem `protobuf:"bytes,1,rep,name=single,proto3" json:"single,omitempty"`
	Multiple             []*ProblemItem `protobuf:"bytes,2,rep,name=multiple,proto3" json:"multiple,omitempty"`
	Fill                 []*ProblemItem `protobuf:"bytes,3,rep,name=fill,proto3" json:"fill,omitempty"`
	Judge                []*ProblemItem `protobuf:"bytes,4,rep,name=judge,proto3" json:"judge,omitempty"`
	BuildFlag            bool           `protobuf:"varint,5,opt,name=buildFlag,proto3" json:"buildFlag,omitempty"`
	AnswerFlag           bool           `protobuf:"varint,6,opt,name=answerFlag,proto3" json:"answerFlag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetProblemNoAnswerRsp) Reset()         { *m = GetProblemNoAnswerRsp{} }
func (m *GetProblemNoAnswerRsp) String() string { return proto.CompactTextString(m) }
func (*GetProblemNoAnswerRsp) ProtoMessage()    {}
func (*GetProblemNoAnswerRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7616ba6b28107807, []int{2}
}

func (m *GetProblemNoAnswerRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProblemNoAnswerRsp.Unmarshal(m, b)
}
func (m *GetProblemNoAnswerRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProblemNoAnswerRsp.Marshal(b, m, deterministic)
}
func (m *GetProblemNoAnswerRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProblemNoAnswerRsp.Merge(m, src)
}
func (m *GetProblemNoAnswerRsp) XXX_Size() int {
	return xxx_messageInfo_GetProblemNoAnswerRsp.Size(m)
}
func (m *GetProblemNoAnswerRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProblemNoAnswerRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetProblemNoAnswerRsp proto.InternalMessageInfo

func (m *GetProblemNoAnswerRsp) GetSingle() []*ProblemItem {
	if m != nil {
		return m.Single
	}
	return nil
}

func (m *GetProblemNoAnswerRsp) GetMultiple() []*ProblemItem {
	if m != nil {
		return m.Multiple
	}
	return nil
}

func (m *GetProblemNoAnswerRsp) GetFill() []*ProblemItem {
	if m != nil {
		return m.Fill
	}
	return nil
}

func (m *GetProblemNoAnswerRsp) GetJudge() []*ProblemItem {
	if m != nil {
		return m.Judge
	}
	return nil
}

func (m *GetProblemNoAnswerRsp) GetBuildFlag() bool {
	if m != nil {
		return m.BuildFlag
	}
	return false
}

func (m *GetProblemNoAnswerRsp) GetAnswerFlag() bool {
	if m != nil {
		return m.AnswerFlag
	}
	return false
}

type ProblemItem struct {
	ProblemId            int64    `protobuf:"varint,1,opt,name=problemId,proto3" json:"problemId,omitempty"`
	Problem              string   `protobuf:"bytes,2,opt,name=problem,proto3" json:"problem,omitempty"`
	Option               string   `protobuf:"bytes,3,opt,name=option,proto3" json:"option,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProblemItem) Reset()         { *m = ProblemItem{} }
func (m *ProblemItem) String() string { return proto.CompactTextString(m) }
func (*ProblemItem) ProtoMessage()    {}
func (*ProblemItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_7616ba6b28107807, []int{3}
}

func (m *ProblemItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemItem.Unmarshal(m, b)
}
func (m *ProblemItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemItem.Marshal(b, m, deterministic)
}
func (m *ProblemItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemItem.Merge(m, src)
}
func (m *ProblemItem) XXX_Size() int {
	return xxx_messageInfo_ProblemItem.Size(m)
}
func (m *ProblemItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemItem.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemItem proto.InternalMessageInfo

func (m *ProblemItem) GetProblemId() int64 {
	if m != nil {
		return m.ProblemId
	}
	return 0
}

func (m *ProblemItem) GetProblem() string {
	if m != nil {
		return m.Problem
	}
	return ""
}

func (m *ProblemItem) GetOption() string {
	if m != nil {
		return m.Option
	}
	return ""
}

func init() {
	proto.RegisterType((*GetProblemNoAnswerReq)(nil), "GetProblemNoAnswerReq")
	proto.RegisterType((*ProblemNum)(nil), "ProblemNum")
	proto.RegisterType((*GetProblemNoAnswerRsp)(nil), "GetProblemNoAnswerRsp")
	proto.RegisterType((*ProblemItem)(nil), "ProblemItem")
}

func init() { proto.RegisterFile("unionManage/unionManage.proto", fileDescriptor_7616ba6b28107807) }

var fileDescriptor_7616ba6b28107807 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x6a, 0xab, 0x40,
	0x14, 0xc6, 0xaf, 0x37, 0x31, 0x37, 0x39, 0x66, 0x75, 0xb8, 0x37, 0x48, 0xb8, 0x2d, 0x41, 0xba,
	0x10, 0x0a, 0x29, 0xa4, 0x4f, 0xd0, 0x4d, 0x8a, 0x8b, 0x96, 0x30, 0x90, 0x65, 0x17, 0xa6, 0x4e,
	0x65, 0xc2, 0x38, 0x33, 0xd5, 0xb1, 0x7d, 0xaf, 0xbe, 0x56, 0x5f, 0xa2, 0x78, 0x34, 0x6a, 0x30,
	0xbb, 0xf9, 0xbe, 0x6f, 0xfe, 0xfc, 0xfc, 0x3c, 0x70, 0x55, 0x2a, 0xa1, 0xd5, 0x53, 0xac, 0xe2,
	0x94, 0xdf, 0xf5, 0xd6, 0x6b, 0x93, 0x6b, 0xab, 0x83, 0x2f, 0x07, 0xfe, 0x3d, 0x72, 0xbb, 0xcb,
	0xf5, 0x41, 0xf2, 0xec, 0x59, 0x3f, 0xa8, 0xe2, 0x93, 0xe7, 0x8c, 0xbf, 0xe3, 0x02, 0x26, 0x65,
	0xc1, 0xf3, 0x28, 0xf1, 0x9d, 0x95, 0x13, 0x8e, 0x58, 0xa3, 0xd0, 0x87, 0x3f, 0xfc, 0x83, 0x2b,
	0x1b, 0x25, 0xfe, 0x6f, 0x0a, 0x4e, 0xb2, 0x3a, 0x61, 0x79, 0x9c, 0x45, 0x89, 0x3f, 0xaa, 0x4f,
	0xd4, 0x0a, 0x03, 0x98, 0x9b, 0xd8, 0x8a, 0x57, 0x61, 0x62, 0x3a, 0x36, 0xa6, 0xf4, 0xcc, 0xc3,
	0x5b, 0x00, 0xd3, 0x30, 0x94, 0x99, 0xef, 0xae, 0x9c, 0xd0, 0xdb, 0x78, 0xeb, 0x5d, 0x6b, 0xb1,
	0x5e, 0x1c, 0x1c, 0x01, 0xba, 0xa4, 0x7a, 0xb6, 0x10, 0x2a, 0x95, 0x9c, 0x40, 0x5d, 0xd6, 0x28,
	0x5c, 0xc2, 0x34, 0x2b, 0xa5, 0x15, 0x46, 0x72, 0x22, 0x75, 0x59, 0xab, 0x11, 0x61, 0xfc, 0x26,
	0xa4, 0x24, 0x50, 0x97, 0xd1, 0x1a, 0xff, 0x82, 0x7b, 0x2c, 0x93, 0x94, 0x13, 0x9f, 0xcb, 0x6a,
	0x11, 0x7c, 0x5f, 0x2e, 0xa8, 0x30, 0x78, 0xd3, 0x7b, 0x77, 0x14, 0x7a, 0x9b, 0xf9, 0x09, 0x37,
	0xb2, 0x3c, 0x6b, 0x29, 0xc2, 0x33, 0x8a, 0xe1, 0xbe, 0x8e, 0x69, 0xd5, 0x32, 0x0d, 0x77, 0xd5,
	0x84, 0x41, 0x47, 0x38, 0xdc, 0x52, 0x47, 0xf8, 0x1f, 0x66, 0x87, 0x52, 0xc8, 0x64, 0x2b, 0xe3,
	0x94, 0x7a, 0x9c, 0xb2, 0xce, 0xc0, 0x6b, 0x80, 0x98, 0x3e, 0x80, 0xe2, 0x09, 0xc5, 0x3d, 0x27,
	0x78, 0x01, 0xaf, 0x77, 0x67, 0x75, 0x59, 0x53, 0x7b, 0x3b, 0x06, 0x9d, 0x51, 0x4d, 0x42, 0x23,
	0xa8, 0xdf, 0x19, 0x3b, 0xc9, 0xea, 0x97, 0x68, 0x63, 0x85, 0x56, 0x54, 0xf0, 0x8c, 0x35, 0x6a,
	0xb3, 0x07, 0x6f, 0xdf, 0x8d, 0x20, 0x6e, 0x01, 0x87, 0xd5, 0xe2, 0x62, 0x7d, 0x71, 0x20, 0x97,
	0x17, 0xfd, 0xc2, 0x04, 0xbf, 0x0e, 0x13, 0x9a, 0xe5, 0xfb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xf9, 0xa3, 0xb7, 0xc2, 0xec, 0x02, 0x00, 0x00,
}
